// ============================================================
// WiT Platform - Seed Content (imported from Claude Design)
// Real curriculum content used as a local fallback when the
// Firestore collections are empty.
// ============================================================

import type { Chapter, Lesson, DictionaryTerm } from './types';
import lessonCongDongChuyenGiaVi from '../content/lesson-cong-thuc-phat-trien-cong-dong-chuyen-gia.vi.md?raw';
import lessonCongDongChuyenGiaEn from '../content/lesson-cong-thuc-phat-trien-cong-dong-chuyen-gia.en.md?raw';
import lessonLuanHoiVi from '../content/lesson-quy-luat-luan-hoi.vi.md?raw';
import lessonLuanHoiEn from '../content/lesson-quy-luat-luan-hoi.en.md?raw';
import lessonNhanQuaVi from '../content/lesson-nhan-thuc-ve-nhan-qua.vi.md?raw';
import lessonNhanQuaEn from '../content/lesson-nhan-thuc-ve-nhan-qua.en.md?raw';
import lessonNLASVi from '../content/lesson-nguyen-ly-anh-sang.vi.md?raw';
import lessonNLASEn from '../content/lesson-nguyen-ly-anh-sang.en.md?raw';
import lessonNLKHNVi from '../content/lesson-nguyen-ly-kich-hoat-nao.vi.md?raw';
import lessonNLKHNEn from '../content/lesson-nguyen-ly-kich-hoat-nao.en.md?raw';
import lessonNLNVVi from '../content/lesson-nguyen-ly-nghi-van.vi.md?raw';
import lessonNLNVEn from '../content/lesson-nguyen-ly-nghi-van.en.md?raw';
import lessonCTCNVi from '../content/lesson-cong-thuc-coi-nguon.vi.md?raw';
import lessonCTCNCTVi from '../content/lesson-cau-truc-con-nguoi-chan-that.vi.md?raw';
import lessonCTCNVGTVi from '../content/lesson-cau-truc-con-nguoi-ve-goi-ten.vi.md?raw';
import lessonCTCNTKVi from '../content/lesson-cau-truc-con-nguoi-tanh-khong.vi.md?raw';
import lessonCTCNTNVi from '../content/lesson-cau-truc-con-nguoi-tanh-nguoi.vi.md?raw';
import lessonCTCN3KDVi from '../content/lesson-cau-truc-con-nguoi-3-khoi-duc.vi.md?raw';
// New imports (l13, l16-l19, l23-l30, l35-l36, l38-l50)
import lessonCTCNVCKTVi from '../content/lesson-cau-truc-con-nguoi-vat-chat-kgian-tgian.vi.md?raw';
import lessonGiauTriTueVi from '../content/lesson-giau-tri-tue.vi.md?raw';
import lessonGiauTamThaiVi from '../content/lesson-giau-tam-thai.vi.md?raw';
import lessonGiauNhanCachVi from '../content/lesson-giau-nhan-cach.vi.md?raw';
import lessonGiauPhamChatVi from '../content/lesson-giau-pham-chat.vi.md?raw';
import lesson7SGTDVi from '../content/lesson-7-su-giau-toan-dien.vi.md?raw';
import lessonNhanTotVi from '../content/lesson-nhan-tot-trong-nhan-sinh.vi.md?raw';
import lesson9DangNguoiVi from '../content/lesson-9-dang-nguoi.vi.md?raw';
import lessonToChatNhanTaiVi from '../content/lesson-nhan-thuc-to-chat-nhan-tai.vi.md?raw';
import lessonNhanThucDuDayVi from '../content/lesson-nhan-thuc-du-day-ve-con-nguoi.vi.md?raw';
import lessonNangCapMQHVi from '../content/lesson-nhan-dang-nang-cap-moi-quan-he.vi.md?raw';
import lesson7BoThiVi from '../content/lesson-7-bo-thi-quan-trong.vi.md?raw';
import lessonDuyenLanhVi from '../content/lesson-duyen-lanh-trong-nhan-sinh.vi.md?raw';
import lessonVuotThoatVi from '../content/lesson-cong-thuc-vuot-thoat-van-nan.vi.md?raw';
import lessonLamGiauVCVi from '../content/lesson-cong-thuc-lam-giau-vat-chat.vi.md?raw';
import lessonBinhThuongPhiThuongVi from '../content/lesson-cong-thuc-bien-binh-thuong-phi-thuong.vi.md?raw';
import lessonTuVanHuanLuyenVi from '../content/lesson-cong-thuc-tu-van-huan-luyen.vi.md?raw';
import lessonMongMuonYThucVi from '../content/lesson-cong-thuc-bien-mong-muon-y-thuc.vi.md?raw';
import lessonKichHoatTongNghiepVi from '../content/lesson-cong-thuc-kich-hoat-tong-nghiep.vi.md?raw';
import lessonTriTueUuTuVi from '../content/lesson-tri-tue-uu-tu.vi.md?raw';
import lessonMatMa3773Vi from '../content/lesson-mat-ma-chuyen-gia-3773.vi.md?raw';
import lessonQuanNiemChuanVi from '../content/lesson-quan-niem-chuan-dao-tao.vi.md?raw';
import lessonTamThaiDungVi from '../content/lesson-tam-thai-dung-dao-tao.vi.md?raw';
import lessonNangLucPhuHopVi from '../content/lesson-nang-luc-phu-hop-dao-tao.vi.md?raw';
import lessonNguyenTacDaoTaoVi from '../content/lesson-nguyen-tac-dao-tao.vi.md?raw';
import lessonThuDacGiaTocVi from '../content/lesson-phuong-phap-thu-dac-gia-toc-tu-chung.vi.md?raw';
import lessonBonDoHinhVi from '../content/lesson-bon-do-hinh-nhan-sinh.vi.md?raw';
import lessonQuyLuatThuHutVi from '../content/lesson-quy-luat-thu-hut-anh-huong-gia-tri.vi.md?raw';
// v2 imports (l12, l14, l15, l20-l22)
import lessonCTCNTNTPVi from '../content/lesson-cau-truc-con-nguoi-tong-nghiep-tiem-thuc.vi.md?raw';
import lessonCTCNTNTPEn from '../content/lesson-cau-truc-con-nguoi-tong-nghiep-tiem-thuc.en.md?raw';
import lessonCTCNTTVi from '../content/lesson-cau-truc-con-nguoi-tam-thuc.vi.md?raw';
import lessonTGHTVi from '../content/lesson-tam-giac-hien-thuc.vi.md?raw';
import lessonGiauNangLucVi from '../content/lesson-giau-nang-luc.vi.md?raw';
import lessonGiauTheChatVi from '../content/lesson-giau-the-chat.vi.md?raw';
import lessonGiauVatChatVi from '../content/lesson-giau-vat-chat.vi.md?raw';
// Phase 3 EN translations imports
import lessonCTCNVCKTEn from '../content/lesson-cau-truc-con-nguoi-vat-chat-kgian-tgian.en.md?raw';
import lessonCTCNTTEn from '../content/lesson-cau-truc-con-nguoi-tam-thuc.en.md?raw';
import lessonTGHTEn from '../content/lesson-tam-giac-hien-thuc.en.md?raw';
import lessonGiauTriTueEn from '../content/lesson-giau-tri-tue.en.md?raw';
import lessonGiauTamThaiEn from '../content/lesson-giau-tam-thai.en.md?raw';
import lessonGiauNhanCachEn from '../content/lesson-giau-nhan-cach.en.md?raw';
import lessonGiauPhamChatEn from '../content/lesson-giau-pham-chat.en.md?raw';
import lessonGiauNangLucEn from '../content/lesson-giau-nang-luc.en.md?raw';
import lessonGiauTheChatEn from '../content/lesson-giau-the-chat.en.md?raw';
import lessonGiauVatChatEn from '../content/lesson-giau-vat-chat.en.md?raw';
import lesson7SGTDEn from '../content/lesson-7-su-giau-toan-dien.en.md?raw';
// Phase 4 EN translations imports
import lessonNhanTotEn from '../content/lesson-nhan-tot-trong-nhan-sinh.en.md?raw';
import lesson9DangNguoiEn from '../content/lesson-9-dang-nguoi.en.md?raw';
import lessonToChatNhanTaiEn from '../content/lesson-nhan-thuc-to-chat-nhan-tai.en.md?raw';
import lessonNhanThucDuDayEn from '../content/lesson-nhan-thuc-du-day-ve-con-nguoi.en.md?raw';
import lessonNangCapMQHEn from '../content/lesson-nhan-dang-nang-cap-moi-quan-he.en.md?raw';
import lesson7BoThiEn from '../content/lesson-7-bo-thi-quan-trong.en.md?raw';
import lessonDuyenLanhEn from '../content/lesson-duyen-lanh-trong-nhan-sinh.en.md?raw';
import lessonQuaNhuYEn from '../content/lesson-qua-nhu-y-trong-nhan-sinh.en.md?raw';
// Phase 5 EN translations imports
import lessonLTBMNTNUMEn from '../content/lesson-lo-trinh-bien-nghe-thanh-nghe-uoc-mo.en.md?raw';
import lessonLTCPLLDTEn from '../content/lesson-lo-trinh-chinh-phuc-luc-loc-dai-thuan.en.md?raw';
import lessonLTNCCGCSEn from '../content/lesson-lo-trinh-nang-cao-canh-gioi-cuoc-song.en.md?raw';
import lessonVuotThoatEn from '../content/lesson-cong-thuc-vuot-thoat-van-nan.en.md?raw';
import lessonLamGiauVCEn from '../content/lesson-cong-thuc-lam-giau-vat-chat.en.md?raw';
import lessonBinhThuongPhiThuongEn from '../content/lesson-cong-thuc-bien-binh-thuong-phi-thuong.en.md?raw';
import lessonTuVanHuanLuyenEn from '../content/lesson-cong-thuc-tu-van-huan-luyen.en.md?raw';
import lessonMongMuonYThucEn from '../content/lesson-cong-thuc-bien-mong-muon-y-thuc.en.md?raw';
import lessonKichHoatTongNghiepEn from '../content/lesson-cong-thuc-kich-hoat-tong-nghiep.en.md?raw';
// Phase 6 EN translations imports
import lessonTriTueUuTuEn from '../content/lesson-tri-tue-uu-tu.en.md?raw';
import lessonMatMa3773En from '../content/lesson-mat-ma-chuyen-gia-3773.en.md?raw';
import lessonQuanNiemChuanEn from '../content/lesson-quan-niem-chuan-dao-tao.en.md?raw';
import lessonTamThaiDungEn from '../content/lesson-tam-thai-dung-dao-tao.en.md?raw';
import lessonNangLucPhuHopEn from '../content/lesson-nang-luc-phu-hop-dao-tao.en.md?raw';
import lessonNguyenTacDaoTaoEn from '../content/lesson-nguyen-tac-dao-tao.en.md?raw';
import lessonThuDacGiaTocEn from '../content/lesson-phuong-phap-thu-dac-gia-toc-tu-chung.en.md?raw';
// v3 imports (l32-l34, l51, l52, l56-l58)
import lessonLTBMNTNUMVi from '../content/lesson-lo-trinh-bien-nghe-thanh-nghe-uoc-mo.vi.md?raw';
import lessonLTCPLLDTVi from '../content/lesson-lo-trinh-chinh-phuc-luc-loc-dai-thuan.vi.md?raw';
import lessonLTNCCGCSVi from '../content/lesson-lo-trinh-nang-cao-canh-gioi-cuoc-song.vi.md?raw';
import lessonQLCSTNSVi from '../content/lesson-quy-luat-cong-sinh-trong-nhan-sinh.vi.md?raw';
import lessonQLTGVi from '../content/lesson-quy-luat-tra-gia.vi.md?raw';
import lessonQLCKVi from '../content/lesson-quy-luat-chu-ky-nguyen-ly-nhip-dieu.vi.md?raw';
import lessonQLCCVi from '../content/lesson-quy-luat-cung-cau.vi.md?raw';
import lessonQLTThucVi from '../content/lesson-quy-luat-tam-thuc.vi.md?raw';
// v4 imports (l59-l76)
import lessonNLCBNVi from '../content/lesson-nguyen-ly-chum-nho-nguyen-ly-buom-tu.vi.md?raw';
import lessonNLVHTCVi from '../content/lesson-nguyen-ly-van-hanh-cua-tiem-thuc.vi.md?raw';
import lessonChiaKhoaVi from '../content/lesson-chia-khoa-ghi-nhan-biet-on-quang-ba.vi.md?raw';
import lessonToiUuTGNVi from '../content/lesson-toi-uu-hoa-thoi-gian-trong-nhan-sinh.vi.md?raw';
import lessonMongMuonTSVi from '../content/lesson-mong-muon-that-su-cua-mot-con-nguoi.vi.md?raw';
import lessonQTTCVi from '../content/lesson-quy-trinh-thanh-cong-cua-nha-lanh-dao-sieu-pham.vi.md?raw';
import lessonLTLaNhDaoVi from '../content/lesson-lo-trinh-tro-thanh-nha-lanh-dao-toan-nang-doanh-nhan-van-hoa.vi.md?raw';
import lessonXDMTLDVi from '../content/lesson-xay-dung-moi-truong-lanh-dao-toan-nang.vi.md?raw';
import lessonCTDinhThanVi from '../content/lesson-chu-trinh-dinh-than.vi.md?raw';
import lessonMasterMentorVi from '../content/lesson-chan-dung-master-mentor-wit.vi.md?raw';
import lessonLoiGiai11QHVi from '../content/lesson-loi-giai-khon-ngoan-cho-11-cau-hoi-nan-giai.vi.md?raw';
import lessonTamDaiPhapBaoVi from '../content/lesson-tam-dai-phap-bao-quang-ba-phoi-hop-dan-dat.vi.md?raw';
import lessonMatMaNQBVi from '../content/lesson-mat-ma-nha-quang-ba.vi.md?raw';
import lessonDiSanVi from '../content/lesson-di-san-cho-the-he-sau.vi.md?raw';
// Phase 8 EN translations imports
import lessonChiaKhoaEn from '../content/lesson-chia-khoa-ghi-nhan-biet-on-quang-ba.en.md?raw';
import lessonToiUuTGNEn from '../content/lesson-toi-uu-hoa-thoi-gian-trong-nhan-sinh.en.md?raw';
import lessonMongMuonTSEn from '../content/lesson-mong-muon-that-su-cua-mot-con-nguoi.en.md?raw';
import lessonQTTCEn from '../content/lesson-quy-trinh-thanh-cong-cua-nha-lanh-dao-sieu-pham.en.md?raw';
import lessonLTLaNhDaoEn from '../content/lesson-lo-trinh-tro-thanh-nha-lanh-dao-toan-nang-doanh-nhan-van-hoa.en.md?raw';
import lessonXDMTLDEn from '../content/lesson-xay-dung-moi-truong-lanh-dao-toan-nang.en.md?raw';
import lessonCTDinhThanEn from '../content/lesson-chu-trinh-dinh-than.en.md?raw';
import lessonMasterMentorEn from '../content/lesson-chan-dung-master-mentor-wit.en.md?raw';
import lessonLoiGiai11QHEn from '../content/lesson-loi-giai-khon-ngoan-cho-11-cau-hoi-nan-giai.en.md?raw';
import lessonTamDaiPhapBaoEn from '../content/lesson-tam-dai-phap-bao-quang-ba-phoi-hop-dan-dat.en.md?raw';
import lessonMatMaNQBEn from '../content/lesson-mat-ma-nha-quang-ba.en.md?raw';
import lessonDiSanEn from '../content/lesson-di-san-cho-the-he-sau.en.md?raw';

import lessonGDNhanThucVi from '../content/lesson-giao-duc-nhan-thuc-giao-duc-tan-goc.vi.md?raw';
import lessonTLGDTGVi from '../content/lesson-triet-ly-giao-duc-tan-goc.vi.md?raw';
import lessonToChucTTVi from '../content/lesson-to-chuc-truong-ton.vi.md?raw';
import lessonSNGiaoDucVi from '../content/lesson-su-nghiep-giao-duc-triet-ly-cho-nhan-sinh.vi.md?raw';

import lessonGDNhanThucEn from '../content/lesson-giao-duc-nhan-thuc-giao-duc-tan-goc.en.md?raw';
import lessonTLGDTGEn from '../content/lesson-triet-ly-giao-duc-tan-goc.en.md?raw';
import lessonToChucTTEn from '../content/lesson-to-chuc-truong-ton.en.md?raw';
import lessonSNGiaoDucEn from '../content/lesson-su-nghiep-giao-duc-triet-ly-cho-nhan-sinh.en.md?raw';

// Phase 7 EN translations imports
import lessonBonDoHinhEn from '../content/lesson-bon-do-hinh-nhan-sinh.en.md?raw';
import lessonQuyLuatThuHutEn from '../content/lesson-quy-luat-thu-hut-anh-huong-gia-tri.en.md?raw';
import lessonQLCSTNSEn from '../content/lesson-quy-luat-cong-sinh-trong-nhan-sinh.en.md?raw';
import lessonQLTGEn from '../content/lesson-quy-luat-tra-gia.en.md?raw';
import lessonBuDapEn from '../content/lesson-quy-luat-bu-dap.en.md?raw';
import lessonThanhTruHoaiDietEn from '../content/lesson-quy-luat-thanh-tru-hoai-diet.en.md?raw';
import lessonQLCKEn from '../content/lesson-quy-luat-chu-ky-nguyen-ly-nhip-dieu.en.md?raw';
import lessonQLCCEn from '../content/lesson-quy-luat-cung-cau.en.md?raw';
import lessonQLTThucEn from '../content/lesson-quy-luat-tam-thuc.en.md?raw';
import lessonNLCBNEn from '../content/lesson-nguyen-ly-chum-nho-nguyen-ly-buom-tu.en.md?raw';
import lessonNLVHTCEn from '../content/lesson-nguyen-ly-van-hanh-cua-tiem-thuc.en.md?raw';
import lessonVongTriThucVi from '../content/lesson-nguyen-ly-vong-tri-thuc.vi.md?raw';
import lessonVongTriThucEn from '../content/lesson-nguyen-ly-vong-tri-thuc.en.md?raw';
import lessonCoiNguonVi from '../content/lesson-cong-thuc-coi-nguon.vi.md?raw';
import lessonCoiNguonEn from '../content/lesson-cong-thuc-coi-nguon.en.md?raw';
import lessonChanThatVi from '../content/lesson-cau-truc-con-nguoi-chan-that.vi.md?raw';
import lessonChanThatEn from '../content/lesson-cau-truc-con-nguoi-chan-that.en.md?raw';
import lessonVeGoiTenVi from '../content/lesson-cau-truc-con-nguoi-ve-goi-ten.vi.md?raw';
import lessonVeGoiTenEn from '../content/lesson-cau-truc-con-nguoi-ve-goi-ten.en.md?raw';
import lessonTanhKhongCtVi from '../content/lesson-cau-truc-con-nguoi-tanh-khong.vi.md?raw';
import lessonTanhKhongCtEn from '../content/lesson-cau-truc-con-nguoi-tanh-khong.en.md?raw';
import lessonTanhNguoiVi from '../content/lesson-cau-truc-con-nguoi-tanh-nguoi.vi.md?raw';
import lessonTanhNguoiEn from '../content/lesson-cau-truc-con-nguoi-tanh-nguoi.en.md?raw';
import lesson3KhoiDucVi from '../content/lesson-cau-truc-con-nguoi-3-khoi-duc.vi.md?raw';
import lesson3KhoiDucEn from '../content/lesson-cau-truc-con-nguoi-3-khoi-duc.en.md?raw';
import lessonQuaNhuYVi from '../content/lesson-qua-nhu-y-trong-nhan-sinh.vi.md?raw';
import lessonBuDapVi from '../content/lesson-quy-luat-bu-dap.vi.md?raw';
import lessonThanhTruHoaiDietVi from '../content/lesson-quy-luat-thanh-tru-hoai-diet.vi.md?raw';
export const SEED_CHAPTERS: Chapter[] = [
  {
    id: 'ch1',
    orderIndex: 1,
    titleVi: 'Nguyên lý Nền tảng',
    titleEn: 'Foundational Principles',
    titleJp: 'Nguyên lý Nền tảng',
    descriptionVi: 'Nhận thức gốc rễ vận hành cuộc sống.',
    descriptionEn: 'Root awareness operating life.',
    descriptionJp: 'Nhận thức gốc rễ vận hành cuộc sống.',
  },
  {
    id: 'ch2',
    orderIndex: 2,
    titleVi: 'Cấu trúc Con người',
    titleEn: 'Human Structure',
    titleJp: 'Cấu trúc Con người',
    descriptionVi: 'Hiểu trọn vẹn về con người bên trong.',
    descriptionEn: 'Fully understand the inner human.',
    descriptionJp: 'Hiểu trọn vẹn về con người bên trong.',
  },
  {
    id: 'ch3',
    orderIndex: 3,
    titleVi: '7 Sự Giàu Toàn Diện',
    titleEn: '7 Dimensions of Holistic Wealth',
    titleJp: '7 Sự Giàu Toàn Diện',
    descriptionVi: 'Bảy chiều giàu có của một đời người.',
    descriptionEn: 'The seven dimensions of wealth in a person\'s life.',
    descriptionJp: 'Bảy chiều giàu có của một đời người.',
  },
  {
    id: 'ch4',
    orderIndex: 4,
    titleVi: 'Nhân tốt & Mối quan hệ',
    titleEn: 'Good Cause & Relationships',
    titleJp: 'Nhân tốt & Mối quan hệ',
    descriptionVi: 'Nhận dạng, thu hút và trở thành người tốt.',
    descriptionEn: 'Identify, attract, and become a good person.',
    descriptionJp: 'Nhận dạng, thu hút và trở thành người tốt.',
  },
  {
    id: 'ch5',
    orderIndex: 5,
    titleVi: 'Lộ trình & Công thức',
    titleEn: 'Roadmap & Formulas',
    titleJp: 'Lộ trình & Công thức',
    descriptionVi: 'Những công thức chuyển hoá cuộc sống.',
    descriptionEn: 'Formulas for life transformation.',
    descriptionJp: 'Những công thức chuyển hoá cuộc sống.',
  },
  {
    id: 'ch6',
    orderIndex: 6,
    titleVi: 'Chuyên gia Tư vấn Nội tâm',
    titleEn: 'Inner Consultation Experts',
    titleJp: 'Chuyên gia Tư vấn Nội tâm',
    descriptionVi: 'Đào tạo bậc chuyên gia huấn luyện nội tâm.',
    descriptionEn: 'Training at the level of inner coaching experts.',
    descriptionJp: 'Đào tạo bậc chuyên gia huấn luyện nội tâm.',
  },
  {
    id: 'ch7',
    orderIndex: 7,
    titleVi: 'Đồ hình & Quy luật Nhân sinh',
    titleEn: 'Diagrams & Laws of Human Life',
    titleJp: 'Đồ hình & Quy luật Nhân sinh',
    descriptionVi: 'Các quy luật vận hành của vũ trụ nhân sinh.',
    descriptionEn: 'The operating laws of the human universe.',
    descriptionJp: 'Các quy luật vận hành của vũ trụ nhân sinh.',
  },
  {
    id: 'ch8',
    orderIndex: 8,
    titleVi: 'Lãnh đạo & Di sản',
    titleEn: 'Leadership & Legacy',
    titleJp: 'Lãnh đạo & Di sản',
    descriptionVi: 'Từ chìa khoá nội tâm đến di sản trường tồn.',
    descriptionEn: 'From inner keys to eternal legacy.',
    descriptionJp: 'Từ chìa khoá nội tâm đến di sản trường tồn.',
  },
  {
    id: 'ch9',
    orderIndex: 9,
    titleVi: 'Giáo dục Tận gốc',
    titleEn: 'Education at the Root',
    titleJp: 'Giáo dục Tận gốc',
    descriptionVi: 'Sự nghiệp giáo dục triết lý cho nhân sinh.',
    descriptionEn: 'The educational career of philosophy for human life.',
    descriptionJp: 'Sự nghiệp giáo dục triết lý cho nhân sinh.',
  },
];

export const SEED_LESSONS: Lesson[] = [
  {
    id: 'l1',
    lessonNo: 1,
    chapterId: 'ch1',
    titleVi: 'Nhận thức về Nhân quả',
    titleEn: 'Awareness of Cause and Effect',
    titleJp: '因果についての認識',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNhanQuaVi,
    contentEn: lessonNhanQuaEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l2',
    lessonNo: 2,
    chapterId: 'ch1',
    titleVi: 'Nguyên lý Ánh sáng trong nhân sinh',
    titleEn: 'The Principle of Light in Human Life',
    titleJp: 'Nguyên lý Ánh sáng trong nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNLASVi,
    contentEn: lessonNLASEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l3',
    lessonNo: 3,
    chapterId: 'ch1',
    titleVi: 'Nguyên lý Kích hoạt não',
    titleEn: 'The Brain Activation Principle',
    titleJp: 'Nguyên lý Kích hoạt não',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNLKHNVi,
    contentEn: lessonNLKHNEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l4',
    lessonNo: 4,
    chapterId: 'ch1',
    titleVi: 'Nguyên lý Nghi vấn thuận chiều mong muốn',
    titleEn: 'The Principle of Inquiry in Line with Desires',
    titleJp: 'Nguyên lý Nghi vấn thuận chiều mong muốn',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNLNVVi,
    contentEn: lessonNLNVEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l5',
    lessonNo: 5,
    chapterId: 'ch1',
    titleVi: 'Nguyên lý Vòng tri thức',
    titleEn: 'The Circle of Knowledge Principle',
    titleJp: 'Nguyên lý Vòng tri thức',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonVongTriThucVi,
    contentEn: lessonVongTriThucEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l6',
    lessonNo: 6,
    chapterId: 'ch1',
    titleVi: 'Công thức cội nguồn cuộc sống',
    titleEn: 'The Formula for the Root Cause of Life',
    titleJp: 'Công thức cội nguồn cuộc sống',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonCoiNguonVi,
    contentEn: lessonCoiNguonEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l7',
    lessonNo: 7,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Chân thật',
    titleEn: 'Human Structure - Truth',
    titleJp: 'Cấu trúc con người - Chân thật',
    summaryVi: '', summaryEn: 'Borrowing the religious perspective to decode the deepest truth within human beings.', summaryJp: '',
    contentVi: lessonChanThatVi,
    contentEn: lessonChanThatEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l8',
    lessonNo: 8,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Vẽ, gọi tên',
    titleEn: 'Human Structure - Drawing and Labelling',
    titleJp: 'Cấu trúc con người - Vẽ, gọi tên',
    summaryVi: '', summaryEn: 'Engraving the four layers (Mind - Nature - Emotion - Body) of human beings in the subconscious through drawing.', summaryJp: '',
    contentVi: lessonVeGoiTenVi,
    contentEn: lessonVeGoiTenEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l9',
    lessonNo: 9,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Tánh không',
    titleEn: 'Human Structure - Emptiness of Nature',
    titleJp: 'Cấu trúc con người - Tánh không',
    summaryVi: '', summaryEn: 'Reaching inner peace and standing above all adversities through the state of Emptiness of Nature.', summaryJp: '',
    contentVi: lessonTanhKhongCtVi,
    contentEn: lessonTanhKhongCtEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l10',
    lessonNo: 10,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Tánh người',
    titleEn: 'Human Structure - 16 Human Natures',
    titleJp: 'Cấu trúc con người - Tánh người',
    summaryVi: '', summaryEn: 'Comprehending the engine of Want and Imagination and the polar electromagnetic amplitude of character.', summaryJp: '',
    contentVi: lessonTanhNguoiVi,
    contentEn: lessonTanhNguoiEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l11',
    lessonNo: 11,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - 3 khối đức',
    titleEn: 'Human Structure - 3 Blocks of Merit',
    titleJp: 'Cấu trúc con người - 3 khối đức',
    summaryVi: '', summaryEn: 'Managing cause and effect, protecting good merit, and viewing humans as merit-accumulating machines.', summaryJp: '',
    contentVi: lesson3KhoiDucVi,
    contentEn: lesson3KhoiDucEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳 là WiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l12',
    lessonNo: 12,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Tổng nghiệp - Nguyên lý vận hành của tiềm thức',
    titleEn: 'Human Structure - Total Karma & Operating Principle of the Subconscious',
    titleJp: 'Cấu trúc con người - Tổng nghiệp - Nguyên lý vận hành của tiềm thức',
    summaryVi: '', summaryEn: 'Accessing untaught knowledge and budding desirable fruits by managing your inner vibration state.', summaryJp: '',
    contentVi: lessonCTCNTNTPVi,
    contentEn: lessonCTCNTNTPEn,
    contentJp: 'これはレッスン「Cấu trúc con người - Tổng nghiệp - Nguyên lý vận hành của tiềm thức」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l13',
    lessonNo: 13,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - vật chất - không gian - thời gian',
    titleEn: 'Human Structure - Matter, Space, Time',
    titleJp: 'Cấu trúc con người - vật chất - không gian - thời gian',
    summaryVi: '',
    summaryEn: 'Understanding the relationship between vibration frequencies, perception of time, and materialization of reality.',
    summaryJp: '',
    contentVi: lessonCTCNVCKTVi,
    contentEn: lessonCTCNVCKTEn,
    contentJp: 'これはレッスン「Cấu trúc con người - vật chất - không gian - thời gian」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l14',
    lessonNo: 14,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Nguyên lý vận hành của tâm thức',
    titleEn: 'Human Structure - Operating Principle of the Mind',
    titleJp: 'Cấu trúc con người - Nguyên lý vận hành của tâm thức',
    summaryVi: '',
    summaryEn: 'Comprehending how messages are received and processed through the layers of Mind, Nature, and Emotion.',
    summaryJp: '',
    contentVi: lessonCTCNTTVi,
    contentEn: lessonCTCNTTEn,
    contentJp: 'これはレッスン「Cấu trúc con người - Nguyên lý vận hành của tâm thức」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l15',
    lessonNo: 15,
    chapterId: 'ch2',
    titleVi: 'Tam giác hiện thực',
    titleEn: 'The Reality Triangle',
    titleJp: 'Tam giác hiện thực',
    summaryVi: '',
    summaryEn: 'Decoding any aspect of life through three corners: Information, Energy, and Materialization.',
    summaryJp: '',
    contentVi: lessonTGHTVi,
    contentEn: lessonTGHTEn,
    contentJp: 'これはレッスン「Tam giác hiện thực」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l16',
    lessonNo: 16,
    chapterId: 'ch3',
    titleVi: 'Giàu Trí tuệ',
    titleEn: 'Wealth of Wisdom',
    titleJp: 'Giàu Trí tuệ',
    summaryVi: '',
    summaryEn: 'Cultivating five levels of inner awareness to rise above all problems in life.',
    summaryJp: '',
    contentVi: lessonGiauTriTueVi,
    contentEn: lessonGiauTriTueEn,
    contentJp: 'これはレッスン「Giàu Trí tuệ」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l17',
    lessonNo: 17,
    chapterId: 'ch3',
    titleVi: 'Giàu Tâm thái',
    titleEn: 'Wealth of Mental State',
    titleJp: 'Giàu Tâm thái',
    summaryVi: '',
    summaryEn: 'Consistently maintaining Honouring & Gratitude at Emotion, Tolerance at Nature, and Inner Peace at Mind.',
    summaryJp: '',
    contentVi: lessonGiauTamThaiVi,
    contentEn: lessonGiauTamThaiEn,
    contentJp: 'これはレッスン「Giàu Tâm thái」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l18',
    lessonNo: 18,
    chapterId: 'ch3',
    titleVi: 'Giàu nhân cách',
    titleEn: 'Wealth of Personality',
    titleJp: 'Giàu nhân cách',
    summaryVi: '',
    summaryEn: 'Nurturing nine core emotional and cognitive states to build a successful environment and retain connections.',
    summaryJp: '',
    contentVi: lessonGiauNhanCachVi,
    contentEn: lessonGiauNhanCachEn,
    contentJp: 'これはレッスン「Giàu nhân cách」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l19',
    lessonNo: 19,
    chapterId: 'ch3',
    titleVi: 'Giàu phẩm chất',
    titleEn: 'Wealth of Qualities',
    titleJp: 'Giàu phẩm chất',
    summaryVi: '',
    summaryEn: 'Cultivating Benevolence, Ritual, Righteousness, Wisdom, and Trustworthiness across the four survival dynamics.',
    summaryJp: '',
    contentVi: lessonGiauPhamChatVi,
    contentEn: lessonGiauPhamChatEn,
    contentJp: 'これはレッスン「Giàu phẩm chất」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l20',
    lessonNo: 20,
    chapterId: 'ch3',
    titleVi: 'Giàu năng lực',
    titleEn: 'Wealth of Capacity',
    titleJp: 'Giàu năng lực',
    summaryVi: '',
    summaryEn: 'Achieving maturity in Concepts, Social Relationships, and Professional Expertise to secure sustainable success.',
    summaryJp: '',
    contentVi: lessonGiauNangLucVi,
    contentEn: lessonGiauNangLucEn,
    contentJp: 'これはレッスン「Giàu năng lực」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l21',
    lessonNo: 21,
    chapterId: 'ch3',
    titleVi: 'Giàu thể chất',
    titleEn: 'Wealth of Physical Body',
    titleJp: 'Giàu thể chất',
    summaryVi: '',
    summaryEn: 'Nurturing a healthy body through natural movement, correct health concepts, and positive mental images.',
    summaryJp: '',
    contentVi: lessonGiauTheChatVi,
    contentEn: lessonGiauTheChatEn,
    contentJp: 'これはレッスン「Giàu thể chất」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l22',
    lessonNo: 22,
    chapterId: 'ch3',
    titleVi: 'Giàu vật chất',
    titleEn: 'Wealth of Material Assets',
    titleJp: 'Giàu vật chất',
    summaryVi: '',
    summaryEn: 'Mastering the 7-step formula and the art of non-materializing to attract and retain financial prosperity.',
    summaryJp: '',
    contentVi: lessonGiauVatChatVi,
    contentEn: lessonGiauVatChatEn,
    contentJp: 'これはレッスン「Giàu vật chất」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l23',
    lessonNo: 23,
    chapterId: 'ch3',
    titleVi: '7 sự Giàu Toàn Diện',
    titleEn: '7 Dimensions of Holistic Wealth',
    titleJp: '7 sự Giàu Toàn Diện',
    summaryVi: '',
    summaryEn: 'Lighting all seven lamps of holistic wealth simultaneously to eliminate all dark corners of life.',
    summaryJp: '',
    contentVi: lesson7SGTDVi,
    contentEn: lesson7SGTDEn,
    contentJp: 'これはレッスン「7 sự Giàu Toàn Diện」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l24',
    lessonNo: 24,
    chapterId: 'ch4',
    titleVi: 'Nhân tốt trong nhân sinh',
    titleEn: 'Good Cause in Human Life',
    titleJp: 'Nhân tốt trong nhân sinh',
    summaryVi: '',
    summaryEn: 'Decoding the root seeds of life through the 3 standard reference systems.',
    summaryJp: '',
    contentVi: lessonNhanTotVi,
    contentEn: lessonNhanTotEn,
    contentJp: 'これはレッスン「Nhân tốt trong nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l25',
    lessonNo: 25,
    chapterId: 'ch4',
    titleVi: '9 dạng người cần nhận dạng, đối đãi, thu hút và trở thành',
    titleEn: '9 Types of People',
    titleJp: '9 dạng người cần nhận dạng, đối đãi, thu hút và trở thành',
    summaryVi: '',
    summaryEn: 'Identifying, treating, attracting, and perfecting ourselves to become the 9 key roles in relationships.',
    summaryJp: '',
    contentVi: lesson9DangNguoiVi,
    contentEn: lesson9DangNguoiEn,
    contentJp: 'これはレッスン「9 dạng người cần nhận dạng, đối đãi, thu hút và trở thành」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l26',
    lessonNo: 26,
    chapterId: 'ch4',
    titleVi: 'Nhận thức về tố chất Nhân tài',
    titleEn: 'Qualities of a Talent',
    titleJp: 'Nhận thức về tố chất Nhân tài',
    summaryVi: '',
    summaryEn: 'Cultivating the 8 core qualities of a talent to nurture outstanding human potential.',
    summaryJp: '',
    contentVi: lessonToChatNhanTaiVi,
    contentEn: lessonToChatNhanTaiEn,
    contentJp: 'これはレッスン「Nhận thức về tố chất Nhân tài」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l27',
    lessonNo: 27,
    chapterId: 'ch4',
    titleVi: 'Nhận thức đủ đầy về Con người',
    titleEn: 'Full Awareness of Human Beings',
    titleJp: 'Nhận thức đủ đầy về Con người',
    summaryVi: '',
    summaryEn: 'Shifting perspectives to view human beings as capital, bridges, teachers, and merits engines.',
    summaryJp: '',
    contentVi: lessonNhanThucDuDayVi,
    contentEn: lessonNhanThucDuDayEn,
    contentJp: 'これはレッスン「Nhận thức đủ đầy về Con người」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l28',
    lessonNo: 28,
    chapterId: 'ch4',
    titleVi: 'Nhận dạng và nâng cấp mối quan hệ',
    titleEn: 'Identifying and Upgrading Relationships',
    titleJp: 'Nhận dạng và nâng cấp mối quan hệ',
    summaryVi: '',
    summaryEn: 'Mastering the 5 relationship levels and the 11 shared elements to upgrade connections.',
    summaryJp: '',
    contentVi: lessonNangCapMQHVi,
    contentEn: lessonNangCapMQHEn,
    contentJp: 'これはレッスン「Nhận dạng và nâng cấp mối quan hệ」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l29',
    lessonNo: 29,
    chapterId: 'ch4',
    titleVi: '7 bố thí quan trọng đời người',
    titleEn: '7 Important Offerings',
    titleJp: '7 bố thí quan trọng đời người',
    summaryVi: '',
    summaryEn: 'Unlocking the 7 offerings to accumulate merits and virtues regardless of financial means.',
    summaryJp: '',
    contentVi: lesson7BoThiVi,
    contentEn: lesson7BoThiEn,
    contentJp: 'これはレッスン「7 bố thí quan trọng đời người」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l30',
    lessonNo: 30,
    chapterId: 'ch4',
    titleVi: 'Duyên lành trong nhân sinh',
    titleEn: 'Good Connection in Human Life',
    titleJp: 'Duyên lành trong nhân sinh',
    summaryVi: '',
    summaryEn: 'Cultivating the soil of relationships through inner peace, tolerance, and gratitude.',
    summaryJp: '',
    contentVi: lessonDuyenLanhVi,
    contentEn: lessonDuyenLanhEn,
    contentJp: 'これはレッスン「Duyên lành trong nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l31',
    lessonNo: 31,
    chapterId: 'ch4',
    titleVi: 'Quả như ý trong nhân sinh',
    titleEn: 'Desirable Outcome in Human Life',
    titleJp: 'Quả như ý trong nhân sinh',
    summaryVi: '',
    summaryEn: 'Activating outcomes through appretell and preserving them through the 5 qualities.',
    summaryJp: '',
    contentVi: lessonQuaNhuYVi,
    contentEn: lessonQuaNhuYEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l32',
    lessonNo: 32,
    chapterId: 'ch5',
    titleVi: 'Lộ trình biến mọi nghề thành Nghề Ước Mơ',
    titleEn: 'Roadmap to Turn Any Job into a Dream Career',
    titleJp: 'Lộ trình biến mọi nghề thành Nghề Ước Mơ',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonLTBMNTNUMVi,
    contentEn: lessonLTBMNTNUMEn,
    contentJp: 'これはレッスン「Lộ trình biến mọi nghề thành Nghề Ước Mơ」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l33',
    lessonNo: 33,
    chapterId: 'ch5',
    titleVi: 'Lộ trình chinh phục cuộc sống Lục Lộc Đại Thuận',
    titleEn: 'Roadmap to Conquer Sixfold Life Fulfillment',
    titleJp: 'Lộ trình chinh phục cuộc sống Lục Lộc Đại Thuận',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonLTCPLLDTVi,
    contentEn: lessonLTCPLLDTEn,
    contentJp: 'これはレッスン「Lộ trình chinh phục cuộc sống Lục Lộc Đại Thuận」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l34',
    lessonNo: 34,
    chapterId: 'ch5',
    titleVi: 'Lộ trình nâng cao Cảnh Giới Cuộc Sống',
    titleEn: 'Roadmap to Elevate the Realm of Life',
    titleJp: 'Lộ trình nâng cao Cảnh Giới Cuộc Sống',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonLTNCCGCSVi,
    contentEn: lessonLTNCCGCSEn,
    contentJp: 'これはレッスン「Lộ trình nâng cao Cảnh Giới Cuộc Sống」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l35',
    lessonNo: 35,
    chapterId: 'ch5',
    titleVi: 'Công thức vượt thoát mọi vấn nạn',
    titleEn: 'Formula for Rising Above All Adversities',
    titleJp: 'Công thức vượt thoát mọi vấn nạn',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonVuotThoatVi,
    contentEn: lessonVuotThoatEn,
    contentJp: 'これはレッスン「Công thức vượt thoát mọi vấn nạn」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l36',
    lessonNo: 36,
    chapterId: 'ch5',
    titleVi: 'Công thức làm giàu vật chất',
    titleEn: 'Formula for Material Wealth',
    titleJp: 'Công thức làm giàu vật chất',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonLamGiauVCVi,
    contentEn: lessonLamGiauVCEn,
    contentJp: 'これはレッスン「Công thức làm giàu vật chất」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l37',
    lessonNo: 37,
    chapterId: 'ch5',
    titleVi: 'Công thức phát triển Cộng đồng Chuyên gia 1-2-20-500-10.000',
    titleEn: 'Formula for Replicating the Expert Community 1-2-20-500-10,000',
    titleJp: 'Công thức phát triển Cộng đồng Chuyên gia 1-2-20-500-10.000',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonCongDongChuyenGiaVi,
    contentEn: lessonCongDongChuyenGiaEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l38',
    lessonNo: 38,
    chapterId: 'ch5',
    titleVi: 'Công thức biến người bình thường trở nên phi thường',
    titleEn: 'Formula for Shifting Ordinary to Extraordinary',
    titleJp: 'Công thức biến người bình thường trở nên phi thường',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonBinhThuongPhiThuongVi,
    contentEn: lessonBinhThuongPhiThuongEn,
    contentJp: 'これはレッスン「Công thức biến người bình thường trở nên phi thường」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l39',
    lessonNo: 39,
    chapterId: 'ch5',
    titleVi: 'Công thức tư vấn huấn luyện của Chuyên gia tư vấn huấn luyện nội tâm',
    titleEn: 'Coaching and Consultation Formulas of Inner Coaches',
    titleJp: 'Công thức tư vấn huấn luyện của Chuyên gia tư vấn huấn luyện nội tâm',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonTuVanHuanLuyenVi,
    contentEn: lessonTuVanHuanLuyenEn,
    contentJp: 'これはレッスン「Công thức tư vấn huấn luyện của Chuyên gia tư vấn huấn luyện nội tâm」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l40',
    lessonNo: 40,
    chapterId: 'ch5',
    titleVi: 'Công thức biến mong muốn ý thức thành niềm tin bản thân',
    titleEn: 'Formula for Shifting Conscious Desires to Inner Belief',
    titleJp: 'Công thức biến mong muốn ý thức thành niềm tin bản thân',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonMongMuonYThucVi,
    contentEn: lessonMongMuonYThucEn,
    contentJp: 'これはレッスン「Công thức biến mong muốn ý thức thành niềm tin bản thân」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l41',
    lessonNo: 41,
    chapterId: 'ch5',
    titleVi: 'Công thức kích hoạt tổng nghiệp như ý',
    titleEn: 'Formula for Activating Desirable Total Karma',
    titleJp: 'Công thức kích hoạt tổng nghiệp như ý',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonKichHoatTongNghiepVi,
    contentEn: lessonKichHoatTongNghiepEn,
    contentJp: 'これはレッスン「Công thức kích hoạt tổng nghiệp như ý」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l42',
    lessonNo: 42,
    chapterId: 'ch6',
    titleVi: 'Trí tuệ ưu tú (Thiết lập, tập hợp, điều hành và phát huy)',
    titleEn: 'Mastermind Group (Establishment, Assembling, Operation, and Maximization)',
    titleJp: 'Trí tuệ ưu tú (Thiết lập, tập hợp, điều hành và phát huy)',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonTriTueUuTuVi,
    contentEn: lessonTriTueUuTuEn,
    contentJp: 'これはレッスン「Trí tuệ ưu tú (Thiết lập, tập hợp, điều hành và phát huy)」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l43',
    lessonNo: 43,
    chapterId: 'ch6',
    titleVi: 'Mật mã của Chuyên gia tư vấn huấn luyện nội tâm (3773)',
    titleEn: 'The Expert’s Code of the Inner Coach (3773)',
    titleJp: 'Mật mã của Chuyên gia tư vấn huấn luyện nội tâm (3773)',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonMatMa3773Vi,
    contentEn: lessonMatMa3773En,
    contentJp: 'これはレッスン「Mật mã của Chuyên gia tư vấn huấn luyện nội tâm (3773)」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l44',
    lessonNo: 44,
    chapterId: 'ch6',
    titleVi: 'Quan niệm chuẩn trong đào tạo',
    titleEn: 'Standard Concepts in Training of the Inner Coach',
    titleJp: 'Quan niệm chuẩn trong đào tạo',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonQuanNiemChuanVi,
    contentEn: lessonQuanNiemChuanEn,
    contentJp: 'これはレッスン「Quan niệm chuẩn trong đào tạo」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l45',
    lessonNo: 45,
    chapterId: 'ch6',
    titleVi: 'Tâm thái đúng trong đào tạo',
    titleEn: 'Right Mental State in Training of the Inner Coach',
    titleJp: 'Tâm thái đúng trong đào tạo',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonTamThaiDungVi,
    contentEn: lessonTamThaiDungEn,
    contentJp: 'これはレッスン「Tâm thái đúng trong đào tạo」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l46',
    lessonNo: 46,
    chapterId: 'ch6',
    titleVi: 'Năng lực phù hợp trong đào tạo',
    titleEn: 'Suitable Capacity in Training of the Inner Coach',
    titleJp: 'Năng lực phù hợp trong đào tạo',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNangLucPhuHopVi,
    contentEn: lessonNangLucPhuHopEn,
    contentJp: 'これはレッスン「Năng lực phù hợp trong đào tạo」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l47',
    lessonNo: 47,
    chapterId: 'ch6',
    titleVi: 'Nguyên tắc trong đào tạo',
    titleEn: 'Principles in Training of the Inner Coach',
    titleJp: 'Nguyên tắc trong đào tạo',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNguyenTacDaoTaoVi,
    contentEn: lessonNguyenTacDaoTaoEn,
    contentJp: 'これはレッスン「Nguyên tắc trong đào tạo」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l48',
    lessonNo: 48,
    chapterId: 'ch6',
    titleVi: 'Phương pháp Thụ đắc - Gia tốc - Tụ chúng',
    titleEn: 'Acquisition - Acceleration - People Gathering Method',
    titleJp: 'Phương pháp Thụ đắc - Gia tốc - Tụ chúng',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonThuDacGiaTocVi,
    contentEn: lessonThuDacGiaTocEn,
    contentJp: 'これはレッスン「Phương pháp Thụ đắc - Gia tốc - Tụ chúng」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l49',
    lessonNo: 49,
    chapterId: 'ch7',
    titleVi: 'Bốn đồ hình nhân sinh 1,2,3,4 và Ứng dụng',
    titleEn: 'Four Diagrams of Human Life 1, 2, 3, 4 and Applications',
    titleJp: 'Bốn đồ hình nhân sinh 1,2,3,4 và Ứng dụng',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonBonDoHinhVi,
    contentEn: lessonBonDoHinhEn,
    contentJp: 'これはレッスン「Bốn đồ hình nhân sinh 1,2,3,4 và Ứng dụng」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l50',
    lessonNo: 50,
    chapterId: 'ch7',
    titleVi: 'Quy luật Thu hút - Ảnh hưởng - Giá trị - Chuyển hóa',
    titleEn: 'Law of Attraction - Influence - Value - Transformation',
    titleJp: 'Quy luật Thu hút - Ảnh hưởng - Giá trị - Chuyển hóa',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonQuyLuatThuHutVi,
    contentEn: lessonQuyLuatThuHutEn,
    contentJp: 'これはレッスン「Quy luật Thu hút - Ảnh hưởng - Giá trị - Chuyển hóa」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l51',
    lessonNo: 51,
    chapterId: 'ch7',
    titleVi: 'Quy luật Cộng sinh trong nhân sinh',
    titleEn: 'Law of Symbiosis in Human Life',
    titleJp: 'Quy luật Cộng sinh trong nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonQLCSTNSVi,
    contentEn: lessonQLCSTNSEn,
    contentJp: 'これはレッスン「Quy luật Cộng sinh trong nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l52',
    lessonNo: 52,
    chapterId: 'ch7',
    titleVi: 'Quy luật Trả giá',
    titleEn: 'Law of Paying the Price',
    titleJp: 'Quy luật Trả giá',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonQLTGVi,
    contentEn: lessonQLTGEn,
    contentJp: 'これはレッスン「Quy luật Trả giá」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l53',
    lessonNo: 53,
    chapterId: 'ch7',
    titleVi: 'Quy luật Bù Đắp',
    titleEn: 'Law of Compensation',
    titleJp: 'Quy luật Bù Đắp',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonBuDapVi,
    contentEn: lessonBuDapEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l54',
    lessonNo: 54,
    chapterId: 'ch7',
    titleVi: 'Quy luật Thành - Trụ - Hoại - Diệt',
    titleEn: 'Law of Arising - Staying - Changing - Vanishing',
    titleJp: 'Quy luật Thành - Trụ - Hoại - Diệt',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonThanhTruHoaiDietVi,
    contentEn: lessonThanhTruHoaiDietEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l55',
    lessonNo: 55,
    chapterId: 'ch7',
    titleVi: 'Quy luật Luân hồi',
    titleEn: 'Law of Reincarnation',
    titleJp: 'Quy luật Luân hồi',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonLuanHoiVi,
    contentEn: lessonLuanHoiEn,
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l56',
    lessonNo: 56,
    chapterId: 'ch7',
    titleVi: 'Quy luật Chu kỳ - Nguyên lý Nhịp điệu',
    titleEn: 'Law of Cycle - Rhythm Principle',
    titleJp: 'Quy luật Chu kỳ - Nguyên lý Nhịp điệu',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonQLCKVi,
    contentEn: lessonQLCKEn,
    contentJp: 'これはレッスン「Quy luật Chu kỳ - Nguyên lý Nhịp điệu」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l57',
    lessonNo: 57,
    chapterId: 'ch7',
    titleVi: 'Quy luật Cung cầu',
    titleEn: 'Law of Supply and Demand',
    titleJp: 'Quy luật Cung cầu',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonQLCCVi,
    contentEn: lessonQLCCEn,
    contentJp: 'これはレッスン「Quy luật Cung cầu」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l58',
    lessonNo: 58,
    chapterId: 'ch7',
    titleVi: 'Quy luật Tâm thức',
    titleEn: 'Law of Consciousness',
    titleJp: 'Quy luật Tâm thức',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonQLTThucVi,
    contentEn: lessonQLTThucEn,
    contentJp: 'これはレッスン「Quy luật Tâm thức」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l59',
    lessonNo: 59,
    chapterId: 'ch7',
    titleVi: 'Nguyên lý chùm nho - Nguyên lý Bướm tụ',
    titleEn: 'Grape Bunch Principle - Butterfly Gathering Principle',
    titleJp: 'Nguyên lý chùm nho - Nguyên lý Bướm tụ',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNLCBNVi,
    contentEn: lessonNLCBNEn,
    contentJp: 'これはレッスン「Nguyên lý chùm nho - Nguyên lý Bướm tụ」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l60',
    lessonNo: 60,
    chapterId: 'ch7',
    titleVi: 'Nguyên lý vận hành của tiềm thức',
    titleEn: 'Operating Principle of the Subconscious',
    titleJp: 'Nguyên lý vận hành của tiềm thức',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNLVHTCVi,
    contentEn: lessonNLVHTCEn,
    contentJp: 'これはレッスン「Nguyên lý vận hành của tiềm thức」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l61',
    lessonNo: 61,
    chapterId: 'ch8',
    titleVi: 'Chìa khóa (Ghi nhận - Biết ơn & Quảng bá)',
    titleEn: 'Key (Recognition - Gratitude & Appretell)',
    titleJp: 'Chìa khóa (Ghi nhận - Biết ơn & Quảng bá)',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonChiaKhoaVi,
    contentEn: lessonChiaKhoaEn,
    contentJp: 'これはレッスン「Chìa khóa (Ghi nhận - Biết ơn & Quảng bá)」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l62',
    lessonNo: 62,
    chapterId: 'ch8',
    titleVi: 'Tối ưu hóa thời gian trong nhân sinh',
    titleEn: 'Time Optimization in Human Life',
    titleJp: 'Tối ưu hóa thời gian trong nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonToiUuTGNVi,
    contentEn: lessonToiUuTGNEn,
    contentJp: 'これはレッスン「Tối ưu hóa thời gian trong nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l63',
    lessonNo: 63,
    chapterId: 'ch8',
    titleVi: 'Mong muốn thật sự của một con người',
    titleEn: 'The True Desires of a Human Being',
    titleJp: 'Mong muốn thật sự của một con người',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonMongMuonTSVi,
    contentEn: lessonMongMuonTSEn,
    contentJp: 'これはレッスン「Mong muốn thật sự của một con người」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l64',
    lessonNo: 64,
    chapterId: 'ch8',
    titleVi: 'Quy trình thành công của nhà Lãnh đạo siêu phàm',
    titleEn: 'Success Process of an Extraordinary Leader',
    titleJp: 'Quy trình thành công của nhà Lãnh đạo siêu phàm',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonQTTCVi,
    contentEn: lessonQTTCEn,
    contentJp: 'これはレッスン「Quy trình thành công của nhà Lãnh đạo siêu phàm」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l65',
    lessonNo: 65,
    chapterId: 'ch8',
    titleVi: 'Lộ trình trở thành nhà Lãnh đạo toàn năng - Doanh nhân văn hóa',
    titleEn: 'Roadmap to Becoming an Omnipotent Leader - Cultural Entrepreneur',
    titleJp: 'Lộ trình trở thành nhà Lãnh đạo toàn năng - Doanh nhân văn hóa',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonLTLaNhDaoVi,
    contentEn: lessonLTLaNhDaoEn,
    contentJp: 'これはレッスン「Lộ trình trở thành nhà Lãnh đạo toàn năng - Doanh nhân văn hóa」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l66',
    lessonNo: 66,
    chapterId: 'ch8',
    titleVi: 'Xây dựng môi trường Lãnh đạo toàn năng',
    titleEn: 'Building an Omnipotent Leadership Environment',
    titleJp: 'Xây dựng môi trường Lãnh đạo toàn năng',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonXDMTLDVi,
    contentEn: lessonXDMTLDEn,
    contentJp: 'これはレッスン「Xây dựng môi trường Lãnh đạo toàn năng」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l67',
    lessonNo: 67,
    chapterId: 'ch8',
    titleVi: 'Chu trình định thân',
    titleEn: 'Self-Anchoring Cycle',
    titleJp: 'Chu trình định thân',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonCTDinhThanVi,
    contentEn: lessonCTDinhThanEn,
    contentJp: 'これはレッスン「Chu trình định thân」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l68',
    lessonNo: 68,
    chapterId: 'ch8',
    titleVi: 'Chân dung Master Mentor WiT',
    titleEn: 'Portrait of WiT Master Mentor',
    titleJp: 'Chân dung Master Mentor WiT',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonMasterMentorVi,
    contentEn: lessonMasterMentorEn,
    contentJp: 'これはレッスン「Chân dung Master Mentor WiT」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l69',
    lessonNo: 69,
    chapterId: 'ch8',
    titleVi: 'Lời giải khôn ngoan cho 11 câu hỏi nan giải',
    titleEn: 'Wise Solutions for 11 Challenging Questions',
    titleJp: 'Lời giải khôn ngoan cho 11 câu hỏi nan giải',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonLoiGiai11QHVi,
    contentEn: lessonLoiGiai11QHEn,
    contentJp: 'これはレッスン「Lời giải khôn ngoan cho 11 câu hỏi nan giải」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l70',
    lessonNo: 70,
    chapterId: 'ch8',
    titleVi: 'Tam đại pháp bảo: Quảng bá - Phối hợp - Dẫn dắt',
    titleEn: 'Three Treasured Methods: Appretell - Coordination - Lead',
    titleJp: 'Tam đại pháp bảo: Quảng bá - Phối hợp - Dẫn dắt',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonTamDaiPhapBaoVi,
    contentEn: lessonTamDaiPhapBaoEn,
    contentJp: 'これはレッスン「Tam đại pháp bảo: Quảng bá - Phối hợp - Dẫn dắt」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l71',
    lessonNo: 71,
    chapterId: 'ch8',
    titleVi: 'Mật mã Nhà Quảng Bá',
    titleEn: 'Code of the Appreteller',
    titleJp: 'Mật mã Nhà Quảng Bá',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonMatMaNQBVi,
    contentEn: lessonMatMaNQBEn,
    contentJp: 'これはレッスン「Mật mã Nhà Quảng Bá」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l72',
    lessonNo: 72,
    chapterId: 'ch8',
    titleVi: 'Di sản cho thế hệ sau',
    titleEn: 'Legacy for Future Generations',
    titleJp: 'Di sản cho thế hệ sau',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonDiSanVi,
    contentEn: lessonDiSanEn,
    contentJp: 'これはレッスン「Di sản cho thế hệ sau」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l73',
    lessonNo: 73,
    chapterId: 'ch9',
    titleVi: 'Giáo dục nhận thức - Giáo dục tận gốc',
    titleEn: 'Cognitive Education - Education at the Root',
    titleJp: 'Giáo dục nhận thức - Giáo dục tận gốc',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonGDNhanThucVi,
    contentEn: lessonGDNhanThucEn,
    contentJp: 'これはレッスン「Giáo dục nhận thức - Giáo dục tận gốc」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l74',
    lessonNo: 74,
    chapterId: 'ch9',
    titleVi: 'Triết lý giáo dục tận gốc',
    titleEn: 'Philosophy of Education at the Root',
    titleJp: 'Triết lý giáo dục tận gốc',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonTLGDTGVi,
    contentEn: lessonTLGDTGEn,
    contentJp: 'これはレッスン「Triết lý giáo dục tận gốc」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l75',
    lessonNo: 75,
    chapterId: 'ch9',
    titleVi: 'Tổ chức trường tồn',
    titleEn: 'Eternal Organization',
    titleJp: 'Tổ chức trường tồn',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonToChucTTVi,
    contentEn: lessonToChucTTEn,
    contentJp: 'これはレッスン「Tổ chức trường tồn」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l76',
    lessonNo: 76,
    chapterId: 'ch9',
    titleVi: 'Sự nghiệp giáo dục triết lý cho nhân sinh',
    titleEn: 'Career of Philosophical Education for Human Life',
    titleJp: 'Sự nghiệp giáo dục triết lý cho nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonSNGiaoDucVi,
    contentEn: lessonSNGiaoDucEn,
    contentJp: 'これはレッスン「Sự nghiệp giáo dục triết lý cho nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
];

export const SEED_TERMS: DictionaryTerm[] = [
  {
    id: 'nhanqua',
    category: 'Quy luật',
    viTerm: 'Nhân quả', viDef: 'Quy luật vận hành: mỗi nguyên nhân đều tạo ra một kết quả tương ứng.', viPos: 'Danh từ', viIpa: 'ɲən kwaː',
    enTerm: 'Cause & Effect', enDef: 'The law that every cause produces a corresponding effect.', enPos: 'Danh từ', enIpa: 'kɔːz ænd ɪˈfekt',
    jpTerm: '因果', jpDef: 'あらゆる原因が対応する結果を生むという法則。', jpPos: 'Danh từ', jpKana: 'いんが · inga',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'nhan',
    category: 'Khái niệm',
    viTerm: 'Nhân', viDef: 'Hạt giống, nguyên nhân ban đầu tạo nên một kết quả.', viPos: 'Danh từ', viIpa: 'ɲən',
    enTerm: 'A cause', enDef: 'The seed or initial cause that gives rise to a result.', enPos: 'Danh từ', enIpa: 'kɔːz',
    jpTerm: '因', jpDef: '結果を生む最初の原因・種。', jpPos: 'Danh từ', jpKana: 'いん · in',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'qua',
    category: 'Khái niệm',
    viTerm: 'Quả', viDef: 'Kết quả gặt được, sinh ra từ nhân đã gieo.', viPos: 'Danh từ', viIpa: 'kwaː',
    enTerm: 'A fruit', enDef: 'The fruit reaped, born from the cause that was sown.', enPos: 'Danh từ', enIpa: 'fruːt',
    jpTerm: '果', jpDef: '蒔いた因から生じる結果。', jpPos: 'Danh từ', jpKana: 'か · ka',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'tongnghiep',
    category: 'Cấu trúc',
    viTerm: 'Tổng nghiệp', viDef: 'Toàn bộ dấu ấn của hành động, lời nói, ý nghĩ được tích luỹ và lưu giữ.', viPos: 'Danh từ', viIpa: 'toŋ ŋiəp',
    enTerm: 'Total Karma', enDef: 'The accumulated imprint of all one\\u2019s actions, words and thoughts.', enPos: 'Danh từ', enIpa: 'ˈtəʊtl ˈkɑːmə',
    jpTerm: '総業', jpDef: '行動・言葉・思いの全ての蓄積された痕跡。', jpPos: 'Danh từ', jpKana: 'そうごう · sōgō',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'tamthuc',
    category: 'Cấu trúc',
    viTerm: 'Tâm thức', viDef: 'Lớp nhận biết sâu, nơi lưu giữ và vận hành mọi dấu ấn nội tâm.', viPos: 'Danh từ', viIpa: 'təm tʰɨk',
    enTerm: 'Mind-consciousness', enDef: 'The deep layer of awareness that stores and runs all inner imprints.', enPos: 'Danh từ', enIpa: 'maɪnd ˈkɒnʃəsnəs',
    jpTerm: '心識', jpDef: '内なる痕跡を保持し働かせる深い意識。', jpPos: 'Danh từ', jpKana: 'しんしき · shinshiki',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'tanhkhong',
    category: 'Cấu trúc',
    viTerm: 'Tánh không', viDef: 'Bản chất không cố định, luôn biến đổi và tương duyên của vạn vật.', viPos: 'Danh từ', viIpa: 'tǎɲ xəwŋ',
    enTerm: 'Emptiness', enDef: 'The non-fixed, ever-changing, interdependent nature of all things.', enPos: 'Danh từ', enIpa: 'ˈemptinəs',
    jpTerm: '空性', jpDef: '万物の固定されず常に変化し相互依存する本性。', jpPos: 'Danh từ', jpKana: 'くうしょう · kūshō',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'anhsang',
    category: 'Nguyên lý',
    viTerm: 'Ánh sáng', viDef: 'Nguồn nhận thức soi rọi, giúp con người thấy rõ và chuyển hoá.', viPos: 'Danh từ', viIpa: 'ǎɲ ʂǎːŋ',
    enTerm: 'Inner Light', enDef: 'The illuminating awareness that lets a person see clearly and transform.', enPos: 'Danh từ', enIpa: 'ˈɪnə laɪt',
    jpTerm: '光', jpDef: '人を明らかにし変容させる照らす意識。', jpPos: 'Danh từ', jpKana: 'ひかり · hikari',
    viImg: '', enImg: '', jpImg: '',
  },
];
