// ============================================================
// WiT Platform - Seed Content (imported from Claude Design)
// Real curriculum content used as a local fallback when the
// Firestore collections are empty.
// ============================================================

import type { Chapter, Lesson, DictionaryTerm } from './types';
import lessonNhanQuaVi from '../content/lesson-nhan-thuc-ve-nhan-qua.vi.md?raw';
import lessonNLASVi from '../content/lesson-nguyen-ly-anh-sang.vi.md?raw';
import lessonNLKHNVi from '../content/lesson-nguyen-ly-kich-hoat-nao.vi.md?raw';
import lessonNLNVVi from '../content/lesson-nguyen-ly-nghi-van.vi.md?raw';
import lessonNLVTTVi from '../content/lesson-nguyen-ly-vong-tri-thuc.vi.md?raw';
import lessonCTCNVi from '../content/lesson-cong-thuc-coi-nguon.vi.md?raw';
import lessonCTCNCTVi from '../content/lesson-cau-truc-con-nguoi-chan-that.vi.md?raw';
import lessonCTCNVGTVi from '../content/lesson-cau-truc-con-nguoi-ve-goi-ten.vi.md?raw';
import lessonCTCNTKVi from '../content/lesson-cau-truc-con-nguoi-tanh-khong.vi.md?raw';
import lessonCTCNTNVi from '../content/lesson-cau-truc-con-nguoi-tanh-nguoi.vi.md?raw';
import lessonCTCN3KDVi from '../content/lesson-cau-truc-con-nguoi-3-khoi-duc.vi.md?raw';

export const SEED_CHAPTERS: Chapter[] = [
  {
    id: 'ch1',
    orderIndex: 1,
    titleVi: 'Nguyên lý Nền tảng',
    titleEn: 'Nguyên lý Nền tảng',
    titleJp: 'Nguyên lý Nền tảng',
    descriptionVi: 'Nhận thức gốc rễ vận hành cuộc sống.',
    descriptionEn: 'Nhận thức gốc rễ vận hành cuộc sống.',
    descriptionJp: 'Nhận thức gốc rễ vận hành cuộc sống.',
  },
  {
    id: 'ch2',
    orderIndex: 2,
    titleVi: 'Cấu trúc Con người',
    titleEn: 'Cấu trúc Con người',
    titleJp: 'Cấu trúc Con người',
    descriptionVi: 'Hiểu trọn vẹn về con người bên trong.',
    descriptionEn: 'Hiểu trọn vẹn về con người bên trong.',
    descriptionJp: 'Hiểu trọn vẹn về con người bên trong.',
  },
  {
    id: 'ch3',
    orderIndex: 3,
    titleVi: '7 Sự Giàu Toàn Diện',
    titleEn: '7 Sự Giàu Toàn Diện',
    titleJp: '7 Sự Giàu Toàn Diện',
    descriptionVi: 'Bảy chiều giàu có của một đời người.',
    descriptionEn: 'Bảy chiều giàu có của một đời người.',
    descriptionJp: 'Bảy chiều giàu có của một đời người.',
  },
  {
    id: 'ch4',
    orderIndex: 4,
    titleVi: 'Nhân tốt & Mối quan hệ',
    titleEn: 'Nhân tốt & Mối quan hệ',
    titleJp: 'Nhân tốt & Mối quan hệ',
    descriptionVi: 'Nhận dạng, thu hút và trở thành người tốt.',
    descriptionEn: 'Nhận dạng, thu hút và trở thành người tốt.',
    descriptionJp: 'Nhận dạng, thu hút và trở thành người tốt.',
  },
  {
    id: 'ch5',
    orderIndex: 5,
    titleVi: 'Lộ trình & Công thức',
    titleEn: 'Lộ trình & Công thức',
    titleJp: 'Lộ trình & Công thức',
    descriptionVi: 'Những công thức chuyển hoá cuộc sống.',
    descriptionEn: 'Những công thức chuyển hoá cuộc sống.',
    descriptionJp: 'Những công thức chuyển hoá cuộc sống.',
  },
  {
    id: 'ch6',
    orderIndex: 6,
    titleVi: 'Chuyên gia Tư vấn Nội tâm',
    titleEn: 'Chuyên gia Tư vấn Nội tâm',
    titleJp: 'Chuyên gia Tư vấn Nội tâm',
    descriptionVi: 'Đào tạo bậc chuyên gia huấn luyện nội tâm.',
    descriptionEn: 'Đào tạo bậc chuyên gia huấn luyện nội tâm.',
    descriptionJp: 'Đào tạo bậc chuyên gia huấn luyện nội tâm.',
  },
  {
    id: 'ch7',
    orderIndex: 7,
    titleVi: 'Đồ hình & Quy luật Nhân sinh',
    titleEn: 'Đồ hình & Quy luật Nhân sinh',
    titleJp: 'Đồ hình & Quy luật Nhân sinh',
    descriptionVi: 'Các quy luật vận hành của vũ trụ nhân sinh.',
    descriptionEn: 'Các quy luật vận hành của vũ trụ nhân sinh.',
    descriptionJp: 'Các quy luật vận hành của vũ trụ nhân sinh.',
  },
  {
    id: 'ch8',
    orderIndex: 8,
    titleVi: 'Lãnh đạo & Di sản',
    titleEn: 'Lãnh đạo & Di sản',
    titleJp: 'Lãnh đạo & Di sản',
    descriptionVi: 'Từ chìa khoá nội tâm đến di sản trường tồn.',
    descriptionEn: 'Từ chìa khoá nội tâm đến di sản trường tồn.',
    descriptionJp: 'Từ chìa khoá nội tâm đến di sản trường tồn.',
  },
  {
    id: 'ch9',
    orderIndex: 9,
    titleVi: 'Giáo dục Tận gốc',
    titleEn: 'Giáo dục Tận gốc',
    titleJp: 'Giáo dục Tận gốc',
    descriptionVi: 'Sự nghiệp giáo dục triết lý cho nhân sinh.',
    descriptionEn: 'Sự nghiệp giáo dục triết lý cho nhân sinh.',
    descriptionJp: 'Sự nghiệp giáo dục triết lý cho nhân sinh.',
  },
];

export const SEED_LESSONS: Lesson[] = [
  {
    id: 'l1',
    lessonNo: 1,
    chapterId: 'ch1',
    titleVi: 'Nhận thức về Nhân quả',
    titleEn: 'Understanding Cause and Effect',
    titleJp: '因果についての認識',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNhanQuaVi,
    contentEn: 'The full content for this lesson is currently available in Vietnamese. The English translation will be updated by the WiT editorial team.',
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l2',
    lessonNo: 2,
    chapterId: 'ch1',
    titleVi: 'Nguyên lý Ánh sáng trong nhân sinh',
    titleEn: 'Nguyên lý Ánh sáng trong nhân sinh',
    titleJp: 'Nguyên lý Ánh sáng trong nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNLASVi,
    contentEn: 'The full content for this lesson is currently available in Vietnamese. The English translation will be updated by the WiT editorial team.',
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l3',
    lessonNo: 3,
    chapterId: 'ch1',
    titleVi: 'Nguyên lý Kích hoạt não',
    titleEn: 'Nguyên lý Kích hoạt não',
    titleJp: 'Nguyên lý Kích hoạt não',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNLKHNVi,
    contentEn: 'The full content for this lesson is currently available in Vietnamese. The English translation will be updated by the WiT editorial team.',
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l4',
    lessonNo: 4,
    chapterId: 'ch1',
    titleVi: 'Nguyên lý Nghi vấn thuận chiều mong muốn',
    titleEn: 'Nguyên lý Nghi vấn thuận chiều mong muốn',
    titleJp: 'Nguyên lý Nghi vấn thuận chiều mong muốn',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: lessonNLNVVi,
    contentEn: 'The full content for this lesson is currently available in Vietnamese. The English translation will be updated by the WiT editorial team.',
    contentJp: 'このレッスンの全内容は現在ベトナム語でご利用いただけます。日本語翻訳はWiT編集チームにより更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l5',
    lessonNo: 5,
    chapterId: 'ch1',
    titleVi: 'Nguyên lý Vòng tri thức',
    titleEn: 'Nguyên lý Vòng tri thức',
    titleJp: 'Nguyên lý Vòng tri thức',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Nguyên lý Vòng tri thức”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Nguyên lý Vòng tri thức”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Nguyên lý Vòng tri thức」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l6',
    lessonNo: 6,
    chapterId: 'ch1',
    titleVi: 'Công thức cội nguồn cuộc sống',
    titleEn: 'Công thức cội nguồn cuộc sống',
    titleJp: 'Công thức cội nguồn cuộc sống',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Công thức cội nguồn cuộc sống”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Công thức cội nguồn cuộc sống”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Công thức cội nguồn cuộc sống」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l7',
    lessonNo: 7,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Chân thật',
    titleEn: 'Cấu trúc con người - Chân thật',
    titleJp: 'Cấu trúc con người - Chân thật',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Cấu trúc con người - Chân thật”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Cấu trúc con người - Chân thật”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Cấu trúc con người - Chân thật」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l8',
    lessonNo: 8,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Vẽ, gọi tên',
    titleEn: 'Cấu trúc con người - Vẽ, gọi tên',
    titleJp: 'Cấu trúc con người - Vẽ, gọi tên',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Cấu trúc con người - Vẽ, gọi tên”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Cấu trúc con người - Vẽ, gọi tên”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Cấu trúc con người - Vẽ, gọi tên」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l9',
    lessonNo: 9,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Tánh không',
    titleEn: 'Cấu trúc con người - Tánh không',
    titleJp: 'Cấu trúc con người - Tánh không',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Cấu trúc con người - Tánh không”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Cấu trúc con người - Tánh không”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Cấu trúc con người - Tánh không」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l10',
    lessonNo: 10,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Tánh người',
    titleEn: 'Cấu trúc con người - Tánh người',
    titleJp: 'Cấu trúc con người - Tánh người',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Cấu trúc con người - Tánh người”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Cấu trúc con người - Tánh người”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Cấu trúc con người - Tánh người」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l11',
    lessonNo: 11,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - 3 khối đức',
    titleEn: 'Cấu trúc con người - 3 khối đức',
    titleJp: 'Cấu trúc con người - 3 khối đức',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Cấu trúc con người - 3 khối đức”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Cấu trúc con người - 3 khối đức”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Cấu trúc con người - 3 khối đức」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l12',
    lessonNo: 12,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Tổng nghiệp - Nguyên lý vận hành của tiềm thức',
    titleEn: 'Cấu trúc con người - Tổng nghiệp - Nguyên lý vận hành của tiềm thức',
    titleJp: 'Cấu trúc con người - Tổng nghiệp - Nguyên lý vận hành của tiềm thức',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Cấu trúc con người - Tổng nghiệp - Nguyên lý vận hành của tiềm thức”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Cấu trúc con người - Tổng nghiệp - Nguyên lý vận hành của tiềm thức”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Cấu trúc con người - Tổng nghiệp - Nguyên lý vận hành của tiềm thức」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l13',
    lessonNo: 13,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - vật chất - không gian - thời gian',
    titleEn: 'Cấu trúc con người - vật chất - không gian - thời gian',
    titleJp: 'Cấu trúc con người - vật chất - không gian - thời gian',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Cấu trúc con người - vật chất - không gian - thời gian”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Cấu trúc con người - vật chất - không gian - thời gian”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Cấu trúc con người - vật chất - không gian - thời gian」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l14',
    lessonNo: 14,
    chapterId: 'ch2',
    titleVi: 'Cấu trúc con người - Nguyên lý vận hành của tâm thức',
    titleEn: 'Cấu trúc con người - Nguyên lý vận hành của tâm thức',
    titleJp: 'Cấu trúc con người - Nguyên lý vận hành của tâm thức',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Cấu trúc con người - Nguyên lý vận hành của tâm thức”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Cấu trúc con người - Nguyên lý vận hành của tâm thức”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Cấu trúc con người - Nguyên lý vận hành của tâm thức」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l15',
    lessonNo: 15,
    chapterId: 'ch2',
    titleVi: 'Tam giác hiện thực',
    titleEn: 'Tam giác hiện thực',
    titleJp: 'Tam giác hiện thực',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Tam giác hiện thực”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Tam giác hiện thực”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Tam giác hiện thực」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l16',
    lessonNo: 16,
    chapterId: 'ch3',
    titleVi: 'Giàu Trí tuệ',
    titleEn: 'Giàu Trí tuệ',
    titleJp: 'Giàu Trí tuệ',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Giàu Trí tuệ”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Giàu Trí tuệ”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Giàu Trí tuệ」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l17',
    lessonNo: 17,
    chapterId: 'ch3',
    titleVi: 'Giàu Tâm thái',
    titleEn: 'Giàu Tâm thái',
    titleJp: 'Giàu Tâm thái',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Giàu Tâm thái”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Giàu Tâm thái”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Giàu Tâm thái」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l18',
    lessonNo: 18,
    chapterId: 'ch3',
    titleVi: 'Giàu nhân cách',
    titleEn: 'Giàu nhân cách',
    titleJp: 'Giàu nhân cách',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Giàu nhân cách”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Giàu nhân cách”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Giàu nhân cách」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l19',
    lessonNo: 19,
    chapterId: 'ch3',
    titleVi: 'Giàu phẩm chất',
    titleEn: 'Giàu phẩm chất',
    titleJp: 'Giàu phẩm chất',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Giàu phẩm chất”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Giàu phẩm chất”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Giàu phẩm chất」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l20',
    lessonNo: 20,
    chapterId: 'ch3',
    titleVi: 'Giàu năng lực',
    titleEn: 'Giàu năng lực',
    titleJp: 'Giàu năng lực',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Giàu năng lực”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Giàu năng lực”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Giàu năng lực」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l21',
    lessonNo: 21,
    chapterId: 'ch3',
    titleVi: 'Giàu thể chất',
    titleEn: 'Giàu thể chất',
    titleJp: 'Giàu thể chất',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Giàu thể chất”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Giàu thể chất”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Giàu thể chất」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l22',
    lessonNo: 22,
    chapterId: 'ch3',
    titleVi: 'Giàu vật chất',
    titleEn: 'Giàu vật chất',
    titleJp: 'Giàu vật chất',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Giàu vật chất”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Giàu vật chất”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Giàu vật chất」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l23',
    lessonNo: 23,
    chapterId: 'ch3',
    titleVi: '7 sự Giàu Toàn Diện',
    titleEn: '7 sự Giàu Toàn Diện',
    titleJp: '7 sự Giàu Toàn Diện',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “7 sự Giàu Toàn Diện”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “7 sự Giàu Toàn Diện”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「7 sự Giàu Toàn Diện」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l24',
    lessonNo: 24,
    chapterId: 'ch4',
    titleVi: 'Nhân tốt trong nhân sinh',
    titleEn: 'Nhân tốt trong nhân sinh',
    titleJp: 'Nhân tốt trong nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Nhân tốt trong nhân sinh”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Nhân tốt trong nhân sinh”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Nhân tốt trong nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l25',
    lessonNo: 25,
    chapterId: 'ch4',
    titleVi: '9 dạng người cần nhận dạng, đối đãi, thu hút và trở thành',
    titleEn: '9 dạng người cần nhận dạng, đối đãi, thu hút và trở thành',
    titleJp: '9 dạng người cần nhận dạng, đối đãi, thu hút và trở thành',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “9 dạng người cần nhận dạng, đối đãi, thu hút và trở thành”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “9 dạng người cần nhận dạng, đối đãi, thu hút và trở thành”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「9 dạng người cần nhận dạng, đối đãi, thu hút và trở thành」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l26',
    lessonNo: 26,
    chapterId: 'ch4',
    titleVi: 'Nhận thức về tố chất Nhân tài',
    titleEn: 'Nhận thức về tố chất Nhân tài',
    titleJp: 'Nhận thức về tố chất Nhân tài',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Nhận thức về tố chất Nhân tài”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Nhận thức về tố chất Nhân tài”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Nhận thức về tố chất Nhân tài」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l27',
    lessonNo: 27,
    chapterId: 'ch4',
    titleVi: 'Nhận thức đủ đầy về Con người',
    titleEn: 'Nhận thức đủ đầy về Con người',
    titleJp: 'Nhận thức đủ đầy về Con người',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Nhận thức đủ đầy về Con người”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Nhận thức đủ đầy về Con người”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Nhận thức đủ đầy về Con người」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l28',
    lessonNo: 28,
    chapterId: 'ch4',
    titleVi: 'Nhận dạng và nâng cấp mối quan hệ',
    titleEn: 'Nhận dạng và nâng cấp mối quan hệ',
    titleJp: 'Nhận dạng và nâng cấp mối quan hệ',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Nhận dạng và nâng cấp mối quan hệ”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Nhận dạng và nâng cấp mối quan hệ”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Nhận dạng và nâng cấp mối quan hệ」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l29',
    lessonNo: 29,
    chapterId: 'ch4',
    titleVi: '7 bố thí quan trọng đời người',
    titleEn: '7 bố thí quan trọng đời người',
    titleJp: '7 bố thí quan trọng đời người',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “7 bố thí quan trọng đời người”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “7 bố thí quan trọng đời người”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「7 bố thí quan trọng đời người」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l30',
    lessonNo: 30,
    chapterId: 'ch4',
    titleVi: 'Duyên lành trong nhân sinh',
    titleEn: 'Duyên lành trong nhân sinh',
    titleJp: 'Duyên lành trong nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Duyên lành trong nhân sinh”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Duyên lành trong nhân sinh”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Duyên lành trong nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l31',
    lessonNo: 31,
    chapterId: 'ch4',
    titleVi: 'Quả như ý trong nhân sinh',
    titleEn: 'Quả như ý trong nhân sinh',
    titleJp: 'Quả như ý trong nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quả như ý trong nhân sinh”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quả như ý trong nhân sinh”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quả như ý trong nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l32',
    lessonNo: 32,
    chapterId: 'ch5',
    titleVi: 'Lộ trình biến mọi nghề thành Nghề Ước Mơ',
    titleEn: 'Lộ trình biến mọi nghề thành Nghề Ước Mơ',
    titleJp: 'Lộ trình biến mọi nghề thành Nghề Ước Mơ',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Lộ trình biến mọi nghề thành Nghề Ước Mơ”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Lộ trình biến mọi nghề thành Nghề Ước Mơ”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Lộ trình biến mọi nghề thành Nghề Ước Mơ」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l33',
    lessonNo: 33,
    chapterId: 'ch5',
    titleVi: 'Lộ trình chinh phục cuộc sống Lục Lộc Đại Thuận',
    titleEn: 'Lộ trình chinh phục cuộc sống Lục Lộc Đại Thuận',
    titleJp: 'Lộ trình chinh phục cuộc sống Lục Lộc Đại Thuận',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Lộ trình chinh phục cuộc sống Lục Lộc Đại Thuận”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Lộ trình chinh phục cuộc sống Lục Lộc Đại Thuận”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Lộ trình chinh phục cuộc sống Lục Lộc Đại Thuận」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l34',
    lessonNo: 34,
    chapterId: 'ch5',
    titleVi: 'Lộ trình nâng cao Cảnh Giới Cuộc Sống',
    titleEn: 'Lộ trình nâng cao Cảnh Giới Cuộc Sống',
    titleJp: 'Lộ trình nâng cao Cảnh Giới Cuộc Sống',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Lộ trình nâng cao Cảnh Giới Cuộc Sống”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Lộ trình nâng cao Cảnh Giới Cuộc Sống”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Lộ trình nâng cao Cảnh Giới Cuộc Sống」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l35',
    lessonNo: 35,
    chapterId: 'ch5',
    titleVi: 'Công thức vượt thoát mọi vấn nạn',
    titleEn: 'Công thức vượt thoát mọi vấn nạn',
    titleJp: 'Công thức vượt thoát mọi vấn nạn',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Công thức vượt thoát mọi vấn nạn”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Công thức vượt thoát mọi vấn nạn”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Công thức vượt thoát mọi vấn nạn」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l36',
    lessonNo: 36,
    chapterId: 'ch5',
    titleVi: 'Công thức làm giàu vật chất',
    titleEn: 'Công thức làm giàu vật chất',
    titleJp: 'Công thức làm giàu vật chất',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Công thức làm giàu vật chất”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Công thức làm giàu vật chất”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Công thức làm giàu vật chất」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l37',
    lessonNo: 37,
    chapterId: 'ch5',
    titleVi: 'Công thức phát triển Cộng đồng Chuyên gia 1-2-20-500-10.000',
    titleEn: 'Công thức phát triển Cộng đồng Chuyên gia 1-2-20-500-10.000',
    titleJp: 'Công thức phát triển Cộng đồng Chuyên gia 1-2-20-500-10.000',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Công thức phát triển Cộng đồng Chuyên gia 1-2-20-500-10.000”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Công thức phát triển Cộng đồng Chuyên gia 1-2-20-500-10.000”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Công thức phát triển Cộng đồng Chuyên gia 1-2-20-500-10.000」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l38',
    lessonNo: 38,
    chapterId: 'ch5',
    titleVi: 'Công thức biến người bình thường trở nên phi thường',
    titleEn: 'Công thức biến người bình thường trở nên phi thường',
    titleJp: 'Công thức biến người bình thường trở nên phi thường',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Công thức biến người bình thường trở nên phi thường”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Công thức biến người bình thường trở nên phi thường”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Công thức biến người bình thường trở nên phi thường」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l39',
    lessonNo: 39,
    chapterId: 'ch5',
    titleVi: 'Công thức tư vấn huấn luyện của Chuyên gia tư vấn huấn luyện nội tâm',
    titleEn: 'Công thức tư vấn huấn luyện của Chuyên gia tư vấn huấn luyện nội tâm',
    titleJp: 'Công thức tư vấn huấn luyện của Chuyên gia tư vấn huấn luyện nội tâm',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Công thức tư vấn huấn luyện của Chuyên gia tư vấn huấn luyện nội tâm”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Công thức tư vấn huấn luyện của Chuyên gia tư vấn huấn luyện nội tâm”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Công thức tư vấn huấn luyện của Chuyên gia tư vấn huấn luyện nội tâm」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l40',
    lessonNo: 40,
    chapterId: 'ch5',
    titleVi: 'Công thức biến mong muốn ý thức thành niềm tin bản thân',
    titleEn: 'Công thức biến mong muốn ý thức thành niềm tin bản thân',
    titleJp: 'Công thức biến mong muốn ý thức thành niềm tin bản thân',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Công thức biến mong muốn ý thức thành niềm tin bản thân”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Công thức biến mong muốn ý thức thành niềm tin bản thân”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Công thức biến mong muốn ý thức thành niềm tin bản thân」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l41',
    lessonNo: 41,
    chapterId: 'ch5',
    titleVi: 'Công thức kích hoạt tổng nghiệp như ý',
    titleEn: 'Công thức kích hoạt tổng nghiệp như ý',
    titleJp: 'Công thức kích hoạt tổng nghiệp như ý',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Công thức kích hoạt tổng nghiệp như ý”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Công thức kích hoạt tổng nghiệp như ý”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Công thức kích hoạt tổng nghiệp như ý」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l42',
    lessonNo: 42,
    chapterId: 'ch6',
    titleVi: 'Trí tuệ ưu tú (Thiết lập, tập hợp, điều hành và phát huy)',
    titleEn: 'Trí tuệ ưu tú (Thiết lập, tập hợp, điều hành và phát huy)',
    titleJp: 'Trí tuệ ưu tú (Thiết lập, tập hợp, điều hành và phát huy)',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Trí tuệ ưu tú (Thiết lập, tập hợp, điều hành và phát huy)”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Trí tuệ ưu tú (Thiết lập, tập hợp, điều hành và phát huy)”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Trí tuệ ưu tú (Thiết lập, tập hợp, điều hành và phát huy)」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l43',
    lessonNo: 43,
    chapterId: 'ch6',
    titleVi: 'Mật mã của Chuyên gia tư vấn huấn luyện nội tâm (3773)',
    titleEn: 'Mật mã của Chuyên gia tư vấn huấn luyện nội tâm (3773)',
    titleJp: 'Mật mã của Chuyên gia tư vấn huấn luyện nội tâm (3773)',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Mật mã của Chuyên gia tư vấn huấn luyện nội tâm (3773)”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Mật mã của Chuyên gia tư vấn huấn luyện nội tâm (3773)”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Mật mã của Chuyên gia tư vấn huấn luyện nội tâm (3773)」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l44',
    lessonNo: 44,
    chapterId: 'ch6',
    titleVi: 'Quan niệm chuẩn trong đào tạo',
    titleEn: 'Quan niệm chuẩn trong đào tạo',
    titleJp: 'Quan niệm chuẩn trong đào tạo',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quan niệm chuẩn trong đào tạo”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quan niệm chuẩn trong đào tạo”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quan niệm chuẩn trong đào tạo」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l45',
    lessonNo: 45,
    chapterId: 'ch6',
    titleVi: 'Tâm thái đúng trong đào tạo',
    titleEn: 'Tâm thái đúng trong đào tạo',
    titleJp: 'Tâm thái đúng trong đào tạo',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Tâm thái đúng trong đào tạo”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Tâm thái đúng trong đào tạo”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Tâm thái đúng trong đào tạo」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l46',
    lessonNo: 46,
    chapterId: 'ch6',
    titleVi: 'Năng lực phù hợp trong đào tạo',
    titleEn: 'Năng lực phù hợp trong đào tạo',
    titleJp: 'Năng lực phù hợp trong đào tạo',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Năng lực phù hợp trong đào tạo”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Năng lực phù hợp trong đào tạo”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Năng lực phù hợp trong đào tạo」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l47',
    lessonNo: 47,
    chapterId: 'ch6',
    titleVi: 'Nguyên tắc trong đào tạo',
    titleEn: 'Nguyên tắc trong đào tạo',
    titleJp: 'Nguyên tắc trong đào tạo',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Nguyên tắc trong đào tạo”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Nguyên tắc trong đào tạo”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Nguyên tắc trong đào tạo」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l48',
    lessonNo: 48,
    chapterId: 'ch6',
    titleVi: 'Phương pháp Thụ đắc - Gia tốc - Tụ chúng',
    titleEn: 'Phương pháp Thụ đắc - Gia tốc - Tụ chúng',
    titleJp: 'Phương pháp Thụ đắc - Gia tốc - Tụ chúng',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Phương pháp Thụ đắc - Gia tốc - Tụ chúng”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Phương pháp Thụ đắc - Gia tốc - Tụ chúng”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Phương pháp Thụ đắc - Gia tốc - Tụ chúng」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l49',
    lessonNo: 49,
    chapterId: 'ch7',
    titleVi: 'Bốn đồ hình nhân sinh 1,2,3,4 và Ứng dụng',
    titleEn: 'Bốn đồ hình nhân sinh 1,2,3,4 và Ứng dụng',
    titleJp: 'Bốn đồ hình nhân sinh 1,2,3,4 và Ứng dụng',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Bốn đồ hình nhân sinh 1,2,3,4 và Ứng dụng”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Bốn đồ hình nhân sinh 1,2,3,4 và Ứng dụng”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Bốn đồ hình nhân sinh 1,2,3,4 và Ứng dụng」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l50',
    lessonNo: 50,
    chapterId: 'ch7',
    titleVi: 'Quy luật Thu hút - Ảnh hưởng - Giá trị - Chuyển hóa',
    titleEn: 'Quy luật Thu hút - Ảnh hưởng - Giá trị - Chuyển hóa',
    titleJp: 'Quy luật Thu hút - Ảnh hưởng - Giá trị - Chuyển hóa',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quy luật Thu hút - Ảnh hưởng - Giá trị - Chuyển hóa”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quy luật Thu hút - Ảnh hưởng - Giá trị - Chuyển hóa”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quy luật Thu hút - Ảnh hưởng - Giá trị - Chuyển hóa」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l51',
    lessonNo: 51,
    chapterId: 'ch7',
    titleVi: 'Quy luật Cộng sinh trong nhân sinh',
    titleEn: 'Quy luật Cộng sinh trong nhân sinh',
    titleJp: 'Quy luật Cộng sinh trong nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quy luật Cộng sinh trong nhân sinh”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quy luật Cộng sinh trong nhân sinh”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quy luật Cộng sinh trong nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l52',
    lessonNo: 52,
    chapterId: 'ch7',
    titleVi: 'Quy luật Trả giá',
    titleEn: 'Quy luật Trả giá',
    titleJp: 'Quy luật Trả giá',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quy luật Trả giá”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quy luật Trả giá”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quy luật Trả giá」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l53',
    lessonNo: 53,
    chapterId: 'ch7',
    titleVi: 'Quy luật Bù Đắp',
    titleEn: 'Quy luật Bù Đắp',
    titleJp: 'Quy luật Bù Đắp',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quy luật Bù Đắp”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quy luật Bù Đắp”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quy luật Bù Đắp」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l54',
    lessonNo: 54,
    chapterId: 'ch7',
    titleVi: 'Quy luật Thành - Trụ - Hoại - Diệt',
    titleEn: 'Quy luật Thành - Trụ - Hoại - Diệt',
    titleJp: 'Quy luật Thành - Trụ - Hoại - Diệt',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quy luật Thành - Trụ - Hoại - Diệt”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quy luật Thành - Trụ - Hoại - Diệt”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quy luật Thành - Trụ - Hoại - Diệt」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l55',
    lessonNo: 55,
    chapterId: 'ch7',
    titleVi: 'Quy luật Luân hồi',
    titleEn: 'Quy luật Luân hồi',
    titleJp: 'Quy luật Luân hồi',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quy luật Luân hồi”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quy luật Luân hồi”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quy luật Luân hồi」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l56',
    lessonNo: 56,
    chapterId: 'ch7',
    titleVi: 'Quy luật Chu kỳ - Nguyên lý Nhịp điệu',
    titleEn: 'Quy luật Chu kỳ - Nguyên lý Nhịp điệu',
    titleJp: 'Quy luật Chu kỳ - Nguyên lý Nhịp điệu',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quy luật Chu kỳ - Nguyên lý Nhịp điệu”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quy luật Chu kỳ - Nguyên lý Nhịp điệu”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quy luật Chu kỳ - Nguyên lý Nhịp điệu」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l57',
    lessonNo: 57,
    chapterId: 'ch7',
    titleVi: 'Quy luật Cung cầu',
    titleEn: 'Quy luật Cung cầu',
    titleJp: 'Quy luật Cung cầu',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quy luật Cung cầu”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quy luật Cung cầu”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quy luật Cung cầu」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l58',
    lessonNo: 58,
    chapterId: 'ch7',
    titleVi: 'Quy luật Tâm thức',
    titleEn: 'Quy luật Tâm thức',
    titleJp: 'Quy luật Tâm thức',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quy luật Tâm thức”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quy luật Tâm thức”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quy luật Tâm thức」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l59',
    lessonNo: 59,
    chapterId: 'ch7',
    titleVi: 'Nguyên lý chùm nho - Nguyên lý Bướm tụ',
    titleEn: 'Nguyên lý chùm nho - Nguyên lý Bướm tụ',
    titleJp: 'Nguyên lý chùm nho - Nguyên lý Bướm tụ',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Nguyên lý chùm nho - Nguyên lý Bướm tụ”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Nguyên lý chùm nho - Nguyên lý Bướm tụ”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Nguyên lý chùm nho - Nguyên lý Bướm tụ」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l60',
    lessonNo: 60,
    chapterId: 'ch7',
    titleVi: 'Nguyên lý vận hành của tiềm thức',
    titleEn: 'Nguyên lý vận hành của tiềm thức',
    titleJp: 'Nguyên lý vận hành của tiềm thức',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Nguyên lý vận hành của tiềm thức”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Nguyên lý vận hành của tiềm thức”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Nguyên lý vận hành của tiềm thức」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l61',
    lessonNo: 61,
    chapterId: 'ch8',
    titleVi: 'Chìa khóa (Ghi nhận - Biết ơn & Quảng bá)',
    titleEn: 'Chìa khóa (Ghi nhận - Biết ơn & Quảng bá)',
    titleJp: 'Chìa khóa (Ghi nhận - Biết ơn & Quảng bá)',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Chìa khóa (Ghi nhận - Biết ơn & Quảng bá)”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Chìa khóa (Ghi nhận - Biết ơn & Quảng bá)”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Chìa khóa (Ghi nhận - Biết ơn & Quảng bá)」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l62',
    lessonNo: 62,
    chapterId: 'ch8',
    titleVi: 'Tối ưu hóa thời gian trong nhân sinh',
    titleEn: 'Tối ưu hóa thời gian trong nhân sinh',
    titleJp: 'Tối ưu hóa thời gian trong nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Tối ưu hóa thời gian trong nhân sinh”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Tối ưu hóa thời gian trong nhân sinh”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Tối ưu hóa thời gian trong nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l63',
    lessonNo: 63,
    chapterId: 'ch8',
    titleVi: 'Mong muốn thật sự của một con người',
    titleEn: 'Mong muốn thật sự của một con người',
    titleJp: 'Mong muốn thật sự của một con người',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Mong muốn thật sự của một con người”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Mong muốn thật sự của một con người”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Mong muốn thật sự của một con người」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l64',
    lessonNo: 64,
    chapterId: 'ch8',
    titleVi: 'Quy trình thành công của nhà Lãnh đạo siêu phàm',
    titleEn: 'Quy trình thành công của nhà Lãnh đạo siêu phàm',
    titleJp: 'Quy trình thành công của nhà Lãnh đạo siêu phàm',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Quy trình thành công của nhà Lãnh đạo siêu phàm”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Quy trình thành công của nhà Lãnh đạo siêu phàm”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Quy trình thành công của nhà Lãnh đạo siêu phàm」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l65',
    lessonNo: 65,
    chapterId: 'ch8',
    titleVi: 'Lộ trình trở thành nhà Lãnh đạo toàn năng - Doanh nhân văn hóa',
    titleEn: 'Lộ trình trở thành nhà Lãnh đạo toàn năng - Doanh nhân văn hóa',
    titleJp: 'Lộ trình trở thành nhà Lãnh đạo toàn năng - Doanh nhân văn hóa',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Lộ trình trở thành nhà Lãnh đạo toàn năng - Doanh nhân văn hóa”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Lộ trình trở thành nhà Lãnh đạo toàn năng - Doanh nhân văn hóa”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Lộ trình trở thành nhà Lãnh đạo toàn năng - Doanh nhân văn hóa」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l66',
    lessonNo: 66,
    chapterId: 'ch8',
    titleVi: 'Xây dựng môi trường Lãnh đạo toàn năng',
    titleEn: 'Xây dựng môi trường Lãnh đạo toàn năng',
    titleJp: 'Xây dựng môi trường Lãnh đạo toàn năng',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Xây dựng môi trường Lãnh đạo toàn năng”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Xây dựng môi trường Lãnh đạo toàn năng”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Xây dựng môi trường Lãnh đạo toàn năng」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l67',
    lessonNo: 67,
    chapterId: 'ch8',
    titleVi: 'Chu trình định thân',
    titleEn: 'Chu trình định thân',
    titleJp: 'Chu trình định thân',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Chu trình định thân”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Chu trình định thân”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Chu trình định thân」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l68',
    lessonNo: 68,
    chapterId: 'ch8',
    titleVi: 'Chân dung Master Mentor WiT',
    titleEn: 'Chân dung Master Mentor WiT',
    titleJp: 'Chân dung Master Mentor WiT',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Chân dung Master Mentor WiT”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Chân dung Master Mentor WiT”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Chân dung Master Mentor WiT」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l69',
    lessonNo: 69,
    chapterId: 'ch8',
    titleVi: 'Lời giải khôn ngoan cho 11 câu hỏi nan giải',
    titleEn: 'Lời giải khôn ngoan cho 11 câu hỏi nan giải',
    titleJp: 'Lời giải khôn ngoan cho 11 câu hỏi nan giải',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Lời giải khôn ngoan cho 11 câu hỏi nan giải”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Lời giải khôn ngoan cho 11 câu hỏi nan giải”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Lời giải khôn ngoan cho 11 câu hỏi nan giải」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l70',
    lessonNo: 70,
    chapterId: 'ch8',
    titleVi: 'Tam đại pháp bảo: Quảng bá - Phối hợp - Dẫn dắt',
    titleEn: 'Tam đại pháp bảo: Quảng bá - Phối hợp - Dẫn dắt',
    titleJp: 'Tam đại pháp bảo: Quảng bá - Phối hợp - Dẫn dắt',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Tam đại pháp bảo: Quảng bá - Phối hợp - Dẫn dắt”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Tam đại pháp bảo: Quảng bá - Phối hợp - Dẫn dắt”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Tam đại pháp bảo: Quảng bá - Phối hợp - Dẫn dắt」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l71',
    lessonNo: 71,
    chapterId: 'ch8',
    titleVi: 'Mật mã Nhà Quảng Bá',
    titleEn: 'Mật mã Nhà Quảng Bá',
    titleJp: 'Mật mã Nhà Quảng Bá',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Mật mã Nhà Quảng Bá”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Mật mã Nhà Quảng Bá”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Mật mã Nhà Quảng Bá」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l72',
    lessonNo: 72,
    chapterId: 'ch8',
    titleVi: 'Di sản cho thế hệ sau',
    titleEn: 'Di sản cho thế hệ sau',
    titleJp: 'Di sản cho thế hệ sau',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Di sản cho thế hệ sau”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Di sản cho thế hệ sau”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Di sản cho thế hệ sau」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l73',
    lessonNo: 73,
    chapterId: 'ch9',
    titleVi: 'Giáo dục nhận thức - Giáo dục tận gốc',
    titleEn: 'Giáo dục nhận thức - Giáo dục tận gốc',
    titleJp: 'Giáo dục nhận thức - Giáo dục tận gốc',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Giáo dục nhận thức - Giáo dục tận gốc”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Giáo dục nhận thức - Giáo dục tận gốc”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Giáo dục nhận thức - Giáo dục tận gốc」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l74',
    lessonNo: 74,
    chapterId: 'ch9',
    titleVi: 'Triết lý giáo dục tận gốc',
    titleEn: 'Triết lý giáo dục tận gốc',
    titleJp: 'Triết lý giáo dục tận gốc',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Triết lý giáo dục tận gốc”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Triết lý giáo dục tận gốc”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Triết lý giáo dục tận gốc」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l75',
    lessonNo: 75,
    chapterId: 'ch9',
    titleVi: 'Tổ chức trường tồn',
    titleEn: 'Tổ chức trường tồn',
    titleJp: 'Tổ chức trường tồn',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Tổ chức trường tồn”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Tổ chức trường tồn”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Tổ chức trường tồn」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'l76',
    lessonNo: 76,
    chapterId: 'ch9',
    titleVi: 'Sự nghiệp giáo dục triết lý cho nhân sinh',
    titleEn: 'Sự nghiệp giáo dục triết lý cho nhân sinh',
    titleJp: 'Sự nghiệp giáo dục triết lý cho nhân sinh',
    summaryVi: '', summaryEn: '', summaryJp: '',
    contentVi: 'Đây là nội dung minh hoạ cho học phần “Sự nghiệp giáo dục triết lý cho nhân sinh”. Nội dung chi tiết của học phần này sẽ được Team biên soạn WiT cập nhật.',
    contentEn: 'This is illustrative content for the lesson “Sự nghiệp giáo dục triết lý cho nhân sinh”. The full content of this lesson will be updated by the WiT editorial team.',
    contentJp: 'これはレッスン「Sự nghiệp giáo dục triết lý cho nhân sinh」の説明用コンテンツです。このレッスンの詳細な内容はWiT編集チームによって更新されます。',
    status: 'published',
    createdAt: new Date(), updatedAt: new Date(),
  },
];

export const SEED_TERMS: DictionaryTerm[] = [
  {
    id: 'nhanqua',
    category: 'Quy luật',
    viTerm: 'Nhân quả', viDef: 'Quy luật vận hành: mỗi nguyên nhân đều tạo ra một kết quả tương ứng.', viPos: 'Danh từ', viIpa: 'ɲən kwaː',
    enTerm: 'Cause & Effect', enDef: 'The law that every cause produces a corresponding effect.', enPos: 'Danh từ', enIpa: 'kɔːz ænd ɪˈfekt',
    jpTerm: '因果', jpDef: 'あらゆる原因が対応する結果を生むという法則。', jpPos: 'Danh từ', jpKana: 'いんが · inga',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'nhan',
    category: 'Khái niệm',
    viTerm: 'Nhân', viDef: 'Hạt giống, nguyên nhân ban đầu tạo nên một kết quả.', viPos: 'Danh từ', viIpa: 'ɲən',
    enTerm: 'A cause', enDef: 'The seed or initial cause that gives rise to a result.', enPos: 'Danh từ', enIpa: 'kɔːz',
    jpTerm: '因', jpDef: '結果を生む最初の原因・種。', jpPos: 'Danh từ', jpKana: 'いん · in',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'qua',
    category: 'Khái niệm',
    viTerm: 'Quả', viDef: 'Kết quả gặt được, sinh ra từ nhân đã gieo.', viPos: 'Danh từ', viIpa: 'kwaː',
    enTerm: 'A fruit', enDef: 'The fruit reaped, born from the cause that was sown.', enPos: 'Danh từ', enIpa: 'fruːt',
    jpTerm: '果', jpDef: '蒔いた因から生じる結果。', jpPos: 'Danh từ', jpKana: 'か · ka',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'tongnghiep',
    category: 'Cấu trúc',
    viTerm: 'Tổng nghiệp', viDef: 'Toàn bộ dấu ấn của hành động, lời nói, ý nghĩ được tích luỹ và lưu giữ.', viPos: 'Danh từ', viIpa: 'toŋ ŋiəp',
    enTerm: 'Total Karma', enDef: 'The accumulated imprint of all one\\u2019s actions, words and thoughts.', enPos: 'Danh từ', enIpa: 'ˈtəʊtl ˈkɑːmə',
    jpTerm: '総業', jpDef: '行動・言葉・思いの全ての蓄積された痕跡。', jpPos: 'Danh từ', jpKana: 'そうごう · sōgō',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'tamthuc',
    category: 'Cấu trúc',
    viTerm: 'Tâm thức', viDef: 'Lớp nhận biết sâu, nơi lưu giữ và vận hành mọi dấu ấn nội tâm.', viPos: 'Danh từ', viIpa: 'təm tʰɨk',
    enTerm: 'Mind-consciousness', enDef: 'The deep layer of awareness that stores and runs all inner imprints.', enPos: 'Danh từ', enIpa: 'maɪnd ˈkɒnʃəsnəs',
    jpTerm: '心識', jpDef: '内なる痕跡を保持し働かせる深い意識。', jpPos: 'Danh từ', jpKana: 'しんしき · shinshiki',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'tanhkhong',
    category: 'Cấu trúc',
    viTerm: 'Tánh không', viDef: 'Bản chất không cố định, luôn biến đổi và tương duyên của vạn vật.', viPos: 'Danh từ', viIpa: 'tǎɲ xəwŋ',
    enTerm: 'Emptiness', enDef: 'The non-fixed, ever-changing, interdependent nature of all things.', enPos: 'Danh từ', enIpa: 'ˈemptinəs',
    jpTerm: '空性', jpDef: '万物の固定されず常に変化し相互依存する本性。', jpPos: 'Danh từ', jpKana: 'くうしょう · kūshō',
    viImg: '', enImg: '', jpImg: '',
  },
  {
    id: 'anhsang',
    category: 'Nguyên lý',
    viTerm: 'Ánh sáng', viDef: 'Nguồn nhận thức soi rọi, giúp con người thấy rõ và chuyển hoá.', viPos: 'Danh từ', viIpa: 'ǎɲ ʂǎːŋ',
    enTerm: 'Inner Light', enDef: 'The illuminating awareness that lets a person see clearly and transform.', enPos: 'Danh từ', enIpa: 'ˈɪnə laɪt',
    jpTerm: '光', jpDef: '人を明らかにし変容させる照らす意識。', jpPos: 'Danh từ', jpKana: 'ひかり · hikari',
    viImg: '', enImg: '', jpImg: '',
  },
];
