// ============================================================
// WiT Platform - Seed Quiz Questions
// Sample self-review questions used as a local fallback when the
// Firestore `quiz_questions` collection is empty.
// ============================================================

import type { QuizQuestion } from './types';

export const SEED_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    lessonNo: 1,
    chapterId: 'ch1',
    questionVi: 'Quy luật Nhân quả nói về điều gì?',
    questionEn: 'What does the law of Cause & Effect describe?',
    optionsVi: [
      'Mỗi nguyên nhân đều tạo ra một kết quả tương ứng',
      'Mọi việc đều xảy ra ngẫu nhiên',
      'Chỉ người giàu mới có nhân tốt',
      'Kết quả không liên quan đến hành động',
    ],
    optionsEn: [
      'Every cause produces a corresponding effect',
      'Everything happens by random chance',
      'Only the wealthy have good causes',
      'Results are unrelated to actions',
    ],
    correctIndex: 0,
    explanationVi: 'Nhân quả là quy luật vận hành: mỗi nguyên nhân (nhân) đều tạo ra một kết quả (quả) tương ứng.',
    explanationEn: 'Cause & Effect is the law that every cause produces a corresponding effect.',
    difficulty: 'easy',
    tags: ['nhanqua'],
    status: 'published',
  },
  {
    id: 'q2',
    lessonNo: 1,
    chapterId: 'ch1',
    questionVi: '“Nhân” trong giáo trình WiT được hiểu là gì?',
    questionEn: 'In the WiT curriculum, what is "Nhân" (a cause)?',
    optionsVi: [
      'Hạt giống, nguyên nhân ban đầu tạo nên một kết quả',
      'Kết quả cuối cùng của hành động',
      'Một loại cảm xúc tiêu cực',
      'Sự may mắn ngẫu nhiên',
    ],
    optionsEn: [
      'The seed or initial cause that gives rise to a result',
      'The final result of an action',
      'A kind of negative emotion',
      'Random luck',
    ],
    correctIndex: 0,
    explanationVi: 'Nhân là hạt giống, nguyên nhân ban đầu tạo nên một kết quả.',
    explanationEn: 'A cause (Nhân) is the seed or initial cause that gives rise to a result.',
    difficulty: 'easy',
    tags: ['nhan'],
    status: 'published',
  },
  {
    id: 'q3',
    lessonNo: 7,
    chapterId: 'ch2',
    questionVi: '“Tổng nghiệp” được mô tả là gì?',
    questionEn: 'What is "Tổng nghiệp" (Total Karma)?',
    optionsVi: [
      'Toàn bộ dấu ấn của hành động, lời nói và ý nghĩ được tích luỹ',
      'Tổng số tiền một người kiếm được',
      'Số bài học đã hoàn thành',
      'Một nghi lễ tôn giáo',
    ],
    optionsEn: [
      'The accumulated imprint of all actions, words and thoughts',
      'The total money a person earns',
      'The number of lessons completed',
      'A religious ritual',
    ],
    correctIndex: 0,
    explanationVi: 'Tổng nghiệp là toàn bộ dấu ấn của hành động, lời nói, ý nghĩ được tích luỹ và lưu giữ.',
    explanationEn: 'Total Karma is the accumulated imprint of all one’s actions, words and thoughts.',
    difficulty: 'medium',
    tags: ['tongnghiep'],
    status: 'published',
  },
  {
    id: 'q4',
    lessonNo: 8,
    chapterId: 'ch2',
    questionVi: '“Tánh không” chỉ điều gì về bản chất của vạn vật?',
    questionEn: 'What does "Emptiness" (Tánh không) say about the nature of all things?',
    optionsVi: [
      'Bản chất không cố định, luôn biến đổi và tương duyên',
      'Mọi thứ đều trống rỗng và vô nghĩa',
      'Không có gì tồn tại thật sự',
      'Vạn vật là bất biến mãi mãi',
    ],
    optionsEn: [
      'The non-fixed, ever-changing, interdependent nature of all things',
      'Everything is empty and meaningless',
      'Nothing truly exists',
      'All things are forever unchanging',
    ],
    correctIndex: 0,
    explanationVi: 'Tánh không là bản chất không cố định, luôn biến đổi và tương duyên của vạn vật.',
    explanationEn: 'Emptiness is the non-fixed, ever-changing, interdependent nature of all things.',
    difficulty: 'medium',
    tags: ['tanhkhong'],
    status: 'published',
  },
  {
    id: 'q5',
    lessonNo: 14,
    chapterId: 'ch2',
    questionVi: '“Tâm thức” là gì trong cấu trúc con người?',
    questionEn: 'What is "Mind-consciousness" (Tâm thức) in the structure of a person?',
    optionsVi: [
      'Lớp nhận biết sâu, nơi lưu giữ và vận hành mọi dấu ấn nội tâm',
      'Phần thân thể vật lý',
      'Trí thông minh để tính toán',
      'Tài sản vật chất của một người',
    ],
    optionsEn: [
      'The deep layer of awareness that stores and runs all inner imprints',
      'The physical body',
      'Intelligence used for calculation',
      'A person’s material wealth',
    ],
    correctIndex: 0,
    explanationVi: 'Tâm thức là lớp nhận biết sâu, nơi lưu giữ và vận hành mọi dấu ấn nội tâm.',
    explanationEn: 'Mind-consciousness is the deep layer of awareness that stores and runs all inner imprints.',
    difficulty: 'medium',
    tags: ['tamthuc'],
    status: 'published',
  },
  {
    id: 'q6',
    chapterId: 'ch1',
    questionVi: '“Ánh sáng” trong nhân sinh tượng trưng cho điều gì?',
    questionEn: 'What does "Inner Light" symbolise in human life?',
    optionsVi: [
      'Nguồn nhận thức soi rọi, giúp con người thấy rõ và chuyển hoá',
      'Ánh nắng mặt trời buổi sáng',
      'Sự nổi tiếng và danh vọng',
      'Một loại năng lượng vật lý',
    ],
    optionsEn: [
      'The illuminating awareness that lets a person see clearly and transform',
      'Morning sunlight',
      'Fame and reputation',
      'A type of physical energy',
    ],
    correctIndex: 0,
    explanationVi: 'Ánh sáng là nguồn nhận thức soi rọi, giúp con người thấy rõ và chuyển hoá.',
    explanationEn: 'Inner Light is the illuminating awareness that lets a person see clearly and transform.',
    difficulty: 'easy',
    tags: ['anhsang'],
    status: 'published',
  },
  {
    id: 'q7',
    chapterId: 'ch3',
    questionVi: 'Chương “7 Sự Giàu Toàn Diện” nói về bao nhiêu chiều giàu có của một đời người?',
    questionEn: 'The chapter "7 Dimensions of Wealth" describes how many dimensions of a person’s richness?',
    optionsVi: ['7', '3', '9', '76'],
    optionsEn: ['7', '3', '9', '76'],
    correctIndex: 0,
    explanationVi: 'Chương 3 trình bày 7 sự giàu toàn diện: trí tuệ, tâm thái, nhân cách, phẩm chất, năng lực, thể chất và vật chất.',
    explanationEn: 'Chapter 3 covers seven dimensions of wealth: wisdom, mindset, character, qualities, abilities, physique and material.',
    difficulty: 'easy',
    tags: ['chapter3'],
    status: 'published',
  },
  {
    id: 'q8',
    chapterId: 'ch1',
    questionVi: 'Giáo trình Nhân Sinh WiT gồm tất cả bao nhiêu học phần?',
    questionEn: 'How many lessons does the WiT life curriculum contain in total?',
    optionsVi: ['76', '9', '49', '100'],
    optionsEn: ['76', '9', '49', '100'],
    correctIndex: 0,
    explanationVi: 'Giáo trình gồm 76 học phần, được sắp xếp trong 9 chương.',
    explanationEn: 'The curriculum has 76 lessons, organised into 9 chapters.',
    difficulty: 'easy',
    tags: ['overview'],
    status: 'published',
  },
  {
    id: 'q9',
    chapterId: 'ch9',
    questionVi: 'Chương cuối (Chương 9) của giáo trình tập trung vào điều gì?',
    questionEn: 'What does the final chapter (Chapter 9) focus on?',
    optionsVi: [
      'Giáo dục tận gốc và để lại di sản trường tồn',
      'Đầu tư tài chính ngắn hạn',
      'Cấu trúc con người',
      'Quy luật Nhân quả cơ bản',
    ],
    optionsEn: [
      'Root education and leaving a lasting legacy',
      'Short-term financial investing',
      'The structure of a person',
      'The basic law of Cause & Effect',
    ],
    correctIndex: 0,
    explanationVi: 'Chương 9 “Giáo dục Tận gốc” nói về sự nghiệp giáo dục triết lý cho nhân sinh và di sản trường tồn.',
    explanationEn: 'Chapter 9, "Root Education", is about the philosophy-education career for humanity and a lasting legacy.',
    difficulty: 'medium',
    tags: ['chapter9'],
    status: 'published',
  },
  {
    id: 'q10',
    lessonNo: 1,
    chapterId: 'ch1',
    questionVi: 'Theo tinh thần Nhân quả, gieo một nhân thiện lành hôm nay sẽ gặt được gì?',
    questionEn: 'In the spirit of Cause & Effect, sowing a wholesome cause today brings what?',
    optionsVi: [
      'Một quả an vui tương ứng',
      'Sự giàu có ngay lập tức',
      'Không có kết quả nào',
      'Một hình phạt',
    ],
    optionsEn: [
      'A corresponding fruit of peace and joy',
      'Instant wealth',
      'No result at all',
      'A punishment',
    ],
    correctIndex: 0,
    explanationVi: 'Gieo một nhân thiện lành hôm nay, là gặt một quả an vui mai sau.',
    explanationEn: 'Sowing a wholesome seed today harvests a peaceful fruit tomorrow.',
    difficulty: 'easy',
    tags: ['nhanqua'],
    status: 'published',
  },
];
