/**
 * Optimize WiT "đồ hình" (diagram) PNGs → WebP for the dictionary visual tab.
 *
 * Reads source PNGs (1414×2000 portrait), emits two WebP sizes:
 *   public/dict-images/thumb/<slug>_<lang>.webp   (gallery card)
 *   public/dict-images/full/<slug>_<lang>.webp    (lightbox)
 * and a bundled manifest at src/data/dictImages.generated.ts.
 *
 * Usage:
 *   npm run images:dict                       # default source dir
 *   DICT_IMG_SRC="/path/to/BIEUDO" npm run images:dict
 */
import sharp from 'sharp';
import * as fs from 'fs';
import * as path from 'path';

// ── Config ───────────────────────────────────────────────────
const SRC_DIR =
  process.env.DICT_IMG_SRC ||
  path.join(process.env.HOME || '~', 'Downloads', 'BIEUDO '); // note: trailing space
const OUT_DIR = path.resolve('public', 'dict-images');
const THUMB_DIR = path.join(OUT_DIR, 'thumb');
const FULL_DIR = path.join(OUT_DIR, 'full');
const MANIFEST_TS = path.resolve('src', 'data', 'dictImages.generated.ts');

const THUMB_WIDTH = 480;
const FULL_WIDTH = 1414; // native; keeps full readability in lightbox
const THUMB_QUALITY = 72;
const FULL_QUALITY = 80;

type Lang = 'vi' | 'en';
interface DiagramEntry {
  slug: string;
  vi: boolean;
  en: boolean;
}

// ── Helpers ──────────────────────────────────────────────────
function parseName(file: string): { slug: string; lang: Lang } | null {
  const m = file.match(/^(.+)_(vi|en)\.png$/i);
  if (!m) return null;
  return { slug: m[1], lang: m[2].toLowerCase() as Lang };
}

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

async function convert(src: string, dest: string, width: number, quality: number) {
  await sharp(src)
    .resize({ width, withoutEnlargement: true })
    .webp({ quality, effort: 5 })
    .toFile(dest);
}

// ── Main ─────────────────────────────────────────────────────
async function main() {
  if (!fs.existsSync(SRC_DIR)) {
    console.error(`❌ Source dir not found: "${SRC_DIR}"`);
    console.error('   Set DICT_IMG_SRC to the folder containing the PNG diagrams.');
    process.exit(1);
  }

  ensureDir(THUMB_DIR);
  ensureDir(FULL_DIR);
  ensureDir(path.dirname(MANIFEST_TS));

  const files = fs.readdirSync(SRC_DIR).filter((f) => /\.png$/i.test(f));
  console.log(`📂 Found ${files.length} PNG files in source.`);

  const bySlug = new Map<string, DiagramEntry>();
  let converted = 0;
  let skipped = 0;
  let thumbBytes = 0;
  let fullBytes = 0;

  for (const file of files) {
    const parsed = parseName(file);
    if (!parsed) {
      console.warn(`  ⚠️  Skipping unrecognized name: ${file}`);
      continue;
    }
    const { slug, lang } = parsed;
    const src = path.join(SRC_DIR, file);
    const thumbOut = path.join(THUMB_DIR, `${slug}_${lang}.webp`);
    const fullOut = path.join(FULL_DIR, `${slug}_${lang}.webp`);

    // Idempotent: skip if output newer than source
    const srcMtime = fs.statSync(src).mtimeMs;
    const upToDate =
      fs.existsSync(thumbOut) &&
      fs.existsSync(fullOut) &&
      fs.statSync(thumbOut).mtimeMs >= srcMtime &&
      fs.statSync(fullOut).mtimeMs >= srcMtime;

    if (upToDate) {
      skipped++;
    } else {
      await convert(src, thumbOut, THUMB_WIDTH, THUMB_QUALITY);
      await convert(src, fullOut, FULL_WIDTH, FULL_QUALITY);
      converted++;
    }
    thumbBytes += fs.statSync(thumbOut).size;
    fullBytes += fs.statSync(fullOut).size;

    const entry = bySlug.get(slug) || { slug, vi: false, en: false };
    entry[lang] = true;
    bySlug.set(slug, entry);
  }

  const entries = [...bySlug.values()].sort((a, b) => a.slug.localeCompare(b.slug));

  // ── Write bundled manifest ───────────────────────────────
  const banner =
    '// AUTO-GENERATED by scripts/optimize-dict-images.ts — do not edit by hand.\n' +
    `// ${entries.length} diagrams. Regenerate with: npm run images:dict\n`;
  const body =
    'export interface DiagramAsset {\n' +
    '  /** filename slug = imgKey(viTerm) for 1:1 terms, or a composite poster id */\n' +
    '  slug: string;\n' +
    '  vi: boolean;\n' +
    '  en: boolean;\n' +
    '}\n\n' +
    `export const DICT_DIAGRAMS: DiagramAsset[] = ${JSON.stringify(entries, null, 2)};\n\n` +
    'export const DICT_DIAGRAM_SLUGS: ReadonlySet<string> = new Set(\n' +
    '  DICT_DIAGRAMS.map((d) => d.slug),\n' +
    ');\n';
  fs.writeFileSync(MANIFEST_TS, banner + '\n' + body);

  // ── Report ───────────────────────────────────────────────
  const mb = (n: number) => (n / 1048576).toFixed(1);
  console.log(`\n✅ Done. ${converted} converted, ${skipped} up-to-date.`);
  console.log(`   ${entries.length} unique diagrams (vi+en).`);
  console.log(`   thumb total: ${mb(thumbBytes)} MB · full total: ${mb(fullBytes)} MB`);
  console.log(`   manifest → ${path.relative(process.cwd(), MANIFEST_TS)}`);
}

main().catch((err) => {
  console.error('❌ Unexpected error:', err);
  process.exit(1);
});
