// AUTO-GENERATED by scripts/optimize-dict-images.ts — do not edit by hand.
// 161 diagrams. Regenerate with: npm run images:dict

export interface DiagramAsset {
  /** filename slug = imgKey(viTerm) for 1:1 terms, or a composite poster id */
  slug: string;
  vi: boolean;
  en: boolean;
}

export const DICT_DIAGRAMS: DiagramAsset[] = [
  {
    "slug": "3_cauhoiquantrongdoinguoi",
    "vi": true,
    "en": true
  },
  {
    "slug": "3_gocnhin",
    "vi": true,
    "en": true
  },
  {
    "slug": "3_Hequychieu",
    "vi": true,
    "en": true
  },
  {
    "slug": "3_hequychieuchuan_KNN",
    "vi": true,
    "en": true
  },
  {
    "slug": "3_hequychieuchuan_nhantot",
    "vi": true,
    "en": true
  },
  {
    "slug": "5_trangthainhanthucnoitam",
    "vi": true,
    "en": true
  },
  {
    "slug": "6_chuvangtronghanhdong",
    "vi": true,
    "en": true
  },
  {
    "slug": "7_bothi",
    "vi": true,
    "en": true
  },
  {
    "slug": "7_nguyenlytrongtuduy",
    "vi": true,
    "en": true
  },
  {
    "slug": "7_sugiautoandien",
    "vi": true,
    "en": true
  },
  {
    "slug": "8_loaituduy",
    "vi": true,
    "en": true
  },
  {
    "slug": "8_tochatnhantai",
    "vi": true,
    "en": true
  },
  {
    "slug": "9_dangnguoi_thanhtuudonguoi",
    "vi": true,
    "en": true
  },
  {
    "slug": "amuN",
    "vi": true,
    "en": true
  },
  {
    "slug": "anvui",
    "vi": true,
    "en": true
  },
  {
    "slug": "anvuitrantrongbieton",
    "vi": true,
    "en": true
  },
  {
    "slug": "baodung",
    "vi": true,
    "en": true
  },
  {
    "slug": "bieuhienvatchat",
    "vi": true,
    "en": true
  },
  {
    "slug": "buongdinh",
    "vi": true,
    "en": true
  },
  {
    "slug": "cachamvominh",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoi_16tanhnguoidaodong",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoi_cacyeutoanhhuongcongducphuocduc",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoi_hatphuocduccongduc",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoi_nghiepmenh",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoi_tamtanhtinh_thongdiep",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoi_tamtanhtinh1",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoi_tamtanhtinhbeanvui",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoi_tengoi3gocnhin",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoi_thamtuong",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoi_tongnghiep",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautrucconnguoichitiet",
    "vi": true,
    "en": true
  },
  {
    "slug": "cautruconnguoi_16tanhnguoi",
    "vi": true,
    "en": true
  },
  {
    "slug": "chanthat",
    "vi": true,
    "en": true
  },
  {
    "slug": "chiakhoaghinhanbieton",
    "vi": true,
    "en": true
  },
  {
    "slug": "chuyenhoa",
    "vi": true,
    "en": true
  },
  {
    "slug": "congducphuocduc",
    "vi": true,
    "en": true
  },
  {
    "slug": "congthuc_coinguoncuocsong",
    "vi": true,
    "en": true
  },
  {
    "slug": "congthuc_coinguoncuocsong_doihinhdoidoi",
    "vi": true,
    "en": true
  },
  {
    "slug": "congthuclamgiauvatchat",
    "vi": true,
    "en": true
  },
  {
    "slug": "congthucquangba",
    "vi": true,
    "en": true
  },
  {
    "slug": "congthucvuotthoatvannan",
    "vi": true,
    "en": true
  },
  {
    "slug": "dinhhinh",
    "vi": true,
    "en": true
  },
  {
    "slug": "dinhmacnhanxung",
    "vi": true,
    "en": true
  },
  {
    "slug": "dongian",
    "vi": true,
    "en": true
  },
  {
    "slug": "dongthuanconnguoi",
    "vi": true,
    "en": true
  },
  {
    "slug": "duchanhthienha",
    "vi": true,
    "en": true
  },
  {
    "slug": "duyenlanh_kichthichvagiu",
    "vi": true,
    "en": true
  },
  {
    "slug": "giaoducsongkinhdoanhcotrietly",
    "vi": true,
    "en": true
  },
  {
    "slug": "giautamthai",
    "vi": true,
    "en": true
  },
  {
    "slug": "goitongnghiepthuc_khotongnghiep",
    "vi": true,
    "en": true
  },
  {
    "slug": "hanhphuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "hanhphucsuckhoehonnhantaichinh",
    "vi": true,
    "en": true
  },
  {
    "slug": "hanhphuctrachnhiemthanhtuu",
    "vi": true,
    "en": true
  },
  {
    "slug": "hanhvituduytamthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "hienthuc_tamgiachienthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "honnhan_nhuybatnhuy",
    "vi": true,
    "en": true
  },
  {
    "slug": "huantap",
    "vi": true,
    "en": true
  },
  {
    "slug": "huusutri_vosutri",
    "vi": true,
    "en": true
  },
  {
    "slug": "khiemton_caylua",
    "vi": true,
    "en": true
  },
  {
    "slug": "kiemthaobanthan",
    "vi": true,
    "en": true
  },
  {
    "slug": "KNN_coloibatloi",
    "vi": true,
    "en": true
  },
  {
    "slug": "KNN_hequichieu",
    "vi": true,
    "en": true
  },
  {
    "slug": "KNN_khainiemnguon",
    "vi": true,
    "en": true
  },
  {
    "slug": "KNN_thamtuongtrongdiemtanhnguoi",
    "vi": true,
    "en": true
  },
  {
    "slug": "KNN_tuduy",
    "vi": true,
    "en": true
  },
  {
    "slug": "lamgiaulamchutronentrothanh",
    "vi": true,
    "en": true
  },
  {
    "slug": "lamvieclamnguoi",
    "vi": true,
    "en": true
  },
  {
    "slug": "langnghe",
    "vi": true,
    "en": true
  },
  {
    "slug": "luanhoi_dinhbuong",
    "vi": true,
    "en": true
  },
  {
    "slug": "mongmuon_thatsu",
    "vi": true,
    "en": true
  },
  {
    "slug": "mongmuon_ythuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "nghethaynoibiet_tiemthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "ngondentritue",
    "vi": true,
    "en": true
  },
  {
    "slug": "nguoigiauchinhphunguoidan",
    "vi": true,
    "en": true
  },
  {
    "slug": "nguoigiauchinhphunguoidan1",
    "vi": true,
    "en": true
  },
  {
    "slug": "nguyenlyanhsang",
    "vi": true,
    "en": true
  },
  {
    "slug": "nguyenlykichhoatnao",
    "vi": true,
    "en": true
  },
  {
    "slug": "nguyenlynhipdieu",
    "vi": true,
    "en": true
  },
  {
    "slug": "nguyenlythuanchieumongmuon",
    "vi": true,
    "en": true
  },
  {
    "slug": "nguyenlyvanhanhtamthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "nguyenlyvanhanhtiemthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "nguyenlyvongtrithuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "nhan",
    "vi": true,
    "en": true
  },
  {
    "slug": "nhanduyenqua_8chude",
    "vi": true,
    "en": true
  },
  {
    "slug": "nhanduyenqua_congthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "nhanquakhonghoito",
    "vi": true,
    "en": true
  },
  {
    "slug": "nhansinhquan_vutruquan_thegioiquan",
    "vi": true,
    "en": true
  },
  {
    "slug": "nhanthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "nhanthuc1",
    "vi": true,
    "en": true
  },
  {
    "slug": "nhanthucduday_hienthucbenvung",
    "vi": true,
    "en": true
  },
  {
    "slug": "nhantot_tamgiachienthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "niemtinbanthan",
    "vi": true,
    "en": true
  },
  {
    "slug": "niemtinbanthan2",
    "vi": true,
    "en": true
  },
  {
    "slug": "phuocduccongducacduc_chitiet",
    "vi": true,
    "en": true
  },
  {
    "slug": "quangba3trongdiem",
    "vi": true,
    "en": true
  },
  {
    "slug": "quangba9doituong",
    "vi": true,
    "en": true
  },
  {
    "slug": "quangbabuctranhloiich",
    "vi": true,
    "en": true
  },
  {
    "slug": "quangbatrithuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "quanhuy_quabatnhuy",
    "vi": true,
    "en": true
  },
  {
    "slug": "quanhuy_tamgiachienthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "quanniemtrongtuduy",
    "vi": true,
    "en": true
  },
  {
    "slug": "quantrinhanqua",
    "vi": true,
    "en": true
  },
  {
    "slug": "quyluat",
    "vi": true,
    "en": true
  },
  {
    "slug": "sohuukhongsohuu",
    "vi": true,
    "en": true
  },
  {
    "slug": "suckhoe-tamgiachienthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "suckhoethechattinthanxahoi",
    "vi": true,
    "en": true
  },
  {
    "slug": "sucphandoan_3cauhoiquantrong",
    "vi": true,
    "en": true
  },
  {
    "slug": "sumenhdammedonglucsinhton",
    "vi": true,
    "en": true
  },
  {
    "slug": "tacdongnhanthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "taisanlon",
    "vi": true,
    "en": true
  },
  {
    "slug": "tamgiacgioi",
    "vi": true,
    "en": true
  },
  {
    "slug": "tamtailuc_laulonlanh_tamgiacgioi",
    "vi": true,
    "en": true
  },
  {
    "slug": "tamthai_tuduy",
    "vi": true,
    "en": true
  },
  {
    "slug": "tamthai_tưduy_3nguyentac",
    "vi": true,
    "en": true
  },
  {
    "slug": "tamthai1",
    "vi": true,
    "en": true
  },
  {
    "slug": "tamthuc_nhanthucnoitam",
    "vi": true,
    "en": true
  },
  {
    "slug": "tanhkhong",
    "vi": true,
    "en": true
  },
  {
    "slug": "thanhcong",
    "vi": true,
    "en": true
  },
  {
    "slug": "thay",
    "vi": true,
    "en": true
  },
  {
    "slug": "thiendaocanman",
    "vi": true,
    "en": true
  },
  {
    "slug": "thoigian",
    "vi": true,
    "en": true
  },
  {
    "slug": "thoigian_quantrongchuaquantrong",
    "vi": true,
    "en": true
  },
  {
    "slug": "thongtin_tamgiachienthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "thuctai",
    "vi": true,
    "en": true
  },
  {
    "slug": "thudacgiatoctuchung",
    "vi": true,
    "en": true
  },
  {
    "slug": "thudacngonngu",
    "vi": true,
    "en": true
  },
  {
    "slug": "thuhutnguonlucxahoi_dangdat",
    "vi": true,
    "en": true
  },
  {
    "slug": "tichcuctieucuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "tien_canhgioicuocsong",
    "vi": true,
    "en": true
  },
  {
    "slug": "tinbietnghivanmongmuon",
    "vi": true,
    "en": true
  },
  {
    "slug": "tinhkhong",
    "vi": true,
    "en": true
  },
  {
    "slug": "tintuong_ghinhanbieton",
    "vi": true,
    "en": true
  },
  {
    "slug": "tintuong_lieudinhlathanh",
    "vi": true,
    "en": true
  },
  {
    "slug": "trangthainoitam_canbang",
    "vi": true,
    "en": true
  },
  {
    "slug": "trantrongbieton_tamgiachienthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "trantrongbieton1",
    "vi": true,
    "en": true
  },
  {
    "slug": "trantrongbietonbaodunganvui",
    "vi": true,
    "en": true
  },
  {
    "slug": "tritue_tamgiachienthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "tritue_thongtin",
    "vi": true,
    "en": true
  },
  {
    "slug": "trituebac1",
    "vi": true,
    "en": true
  },
  {
    "slug": "trituebac1_chudong",
    "vi": true,
    "en": true
  },
  {
    "slug": "trituebac2",
    "vi": true,
    "en": true
  },
  {
    "slug": "trituebac2_chudongkientao",
    "vi": true,
    "en": true
  },
  {
    "slug": "trituebac3",
    "vi": true,
    "en": true
  },
  {
    "slug": "trituebac3_anvuithanhtinh",
    "vi": true,
    "en": true
  },
  {
    "slug": "trituebac3_khonglaai",
    "vi": true,
    "en": true
  },
  {
    "slug": "trituebac3_tamgiachienthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "trituebac3_tinhkhong",
    "vi": true,
    "en": true
  },
  {
    "slug": "trituebac4_5",
    "vi": true,
    "en": true
  },
  {
    "slug": "tugiachuongdensutotdep",
    "vi": true,
    "en": true
  },
  {
    "slug": "tunhienbiet",
    "vi": true,
    "en": true
  },
  {
    "slug": "uutien",
    "vi": true,
    "en": true
  },
  {
    "slug": "uyenbackhonngoanthongthaitritue",
    "vi": true,
    "en": true
  },
  {
    "slug": "vatchat_phivatchat",
    "vi": true,
    "en": true
  },
  {
    "slug": "vatchatkhonggian_tuongdongthisohuu",
    "vi": true,
    "en": true
  },
  {
    "slug": "vatchatkhonggianthoigian",
    "vi": true,
    "en": true
  },
  {
    "slug": "vuive_anvui",
    "vi": true,
    "en": true
  },
  {
    "slug": "withome",
    "vi": true,
    "en": true
  },
  {
    "slug": "xaydunggopy",
    "vi": true,
    "en": true
  },
  {
    "slug": "ynghethaynoibiet_tamgiachienthuc",
    "vi": true,
    "en": true
  },
  {
    "slug": "yniemduong",
    "vi": true,
    "en": true
  }
];

export const DICT_DIAGRAM_SLUGS: ReadonlySet<string> = new Set(
  DICT_DIAGRAMS.map((d) => d.slug),
);
